Repository pingcap/br, pull requests merged in 2019-12, with the labels that each got.

#84 Remove meta package and make br easy to integrate to other project
  cmd/backup.go
  cmd/cmd.go
  cmd/restore.go
  pkg/backup/client.go
  pkg/backup/client_test.go
  pkg/backup/push.go
  pkg/backup/range_tree.go
  pkg/backup/safe_point.go
  pkg/backup/safe_point_test.go
  pkg/conn/conn.go
  pkg/conn/conn_test.go
  pkg/meta/meta.go
  pkg/meta/meta_test.go
  pkg/restore/client.go
  pkg/restore/client_test.go
  pkg/restore/db.go
  pkg/restore/util.go
  pkg/utils/mock_cluster.go
  pkg/utils/tso.go
  pkg/utils/tso_test.go
Labels: LGT1

#96 README: add more badges
  README.md
  images/arch.svg
Labels: LGT1

#98 conn: close domain before closing storage
  pkg/conn/conn.go
Labels: LGT1

#88 *: extract storage package, and update kvproto
  cmd/backup.go
  cmd/cmd.go
  cmd/meta.go
  cmd/restore.go
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/storage/flags.go
  pkg/storage/local.go
  pkg/storage/local_unix.go
  pkg/storage/local_windows.go
  pkg/storage/noop.go
  pkg/storage/parse.go
  pkg/storage/parse_test.go
  pkg/storage/s3.go
  pkg/storage/storage.go
  pkg/utils/storage.go
  pkg/utils/storage_test.go
Labels: LGT1

#94 tests: test restore db
  tests/br_db/run.sh
  tests/br_key_locked/workload
Labels: LGT1

#99 restore: skip to switch mode when online
  cmd/restore.go
  pkg/restore/client.go
  pkg/restore/client_test.go
Labels: LGT2

#100 restore: add rateLimit for flow control
  cmd/restore.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/utils/unit.go
  tests/br_full/run.sh
Labels: LGT1

#103 backup: store backupmeta to s3
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/storage/flags.go
  pkg/storage/parse.go
  pkg/storage/parse_test.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
Labels: LGT2

#110 GCS: use minus but not underline in config.
  pkg/storage/gcs.go
Labels: LGT1

#118 *: use summary log
  cmd/backup.go
  cmd/restore.go
  pkg/backup/client.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/restore/util.go
  pkg/summary/collector.go
  pkg/summary/summary.go
Labels: WIP

#120 Update release 3.1
  cmd/backup.go
  cmd/restore.go
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/backup/safe_point.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/restore/util.go
  pkg/storage/flags.go
  pkg/storage/gcs.go
  pkg/storage/gcs_test.go
  pkg/storage/parse_test.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
  pkg/summary/collector.go
  pkg/summary/summary.go
Labels: WIP

#123 restore: auto remove/add pd scheduler in restore
  cmd/backup.go
  cmd/cmd.go
  cmd/restore.go
  pkg/conn/conn.go
  pkg/conn/conn_test.go
  pkg/restore/client.go
  pkg/restore/client_test.go
Labels: LGT1, enhancement

#127 conn: fix inaccurate region count
  pkg/conn/conn.go
  pkg/conn/conn_test.go
Labels: LGT1

#128 validate: debug backupmeta
  cmd/validate.go
  pkg/backup/client.go
  pkg/backup/schema.go
  pkg/utils/schema.go
  tests/br_debug_meta/run.sh
Labels: LGT1, enhancement

#129 restore: add scatter region time limit
  go.mod
  go.sum
Labels: LGT1
