Repository pingcap/br, pull requests merged in 2020-10, with the labels that each got.

#548 storage: S3 test refactoring and fix some bugs
  go.mod
  go.sum
  pkg/mock/s3iface.go
  pkg/storage/gcs.go
  pkg/storage/gcs_test.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
Labels: needs-cherry-pick-4.0, status/LGT2

#546 *: allow config the concurrency of checksumming
  pkg/backup/schema.go
  pkg/backup/schema_test.go
  pkg/checksum/executor.go
  pkg/checksum/executor_test.go
  pkg/restore/client.go
  pkg/task/backup.go
  pkg/task/common.go
  pkg/task/restore.go
Labels: needs-cherry-pick-4.0, status/LGT2

#427 restore: make split and restore pipelined.
  pkg/restore/batcher.go
  pkg/restore/batcher_test.go
  pkg/restore/client.go
  pkg/restore/pipeline_items.go
  pkg/restore/util.go
  pkg/utils/logging.go
Labels: CanMerge, needs-cherry-pick-4.0, status/LGT2

#553 checksum: fix checksum gc life time excceed issue
  pkg/backup/client.go
  pkg/restore/split_client.go
  pkg/task/backup.go
  pkg/task/restore.go
  pkg/utils/safe_point.go
  pkg/utils/safe_point_test.go
Labels: CanMerge, status/LGT2

#552 *: strip PD urls with http or https
  pkg/task/common.go
  pkg/task/common_test.go
  tests/br_full/run.sh
  tests/br_tls/run.sh
Labels: status/LGT2

#554 Makefile: hide go.mod to resolve cyclic dependency with tidb
  .gitignore
  Makefile
  go.mod1
  go.sum1
Labels: status/LGT2

#551 scheduler: use pause instead of remove schedulers
  cmd/debug.go
  pkg/pdutil/pd.go
  pkg/pdutil/pd_test.go
  tests/br_other/run.sh
Labels: needs-cherry-pick-4.0, status/LGT2

#559 *: when cleaning up, use isolated context
  Makefile
  main.go
  pkg/gluetikv/glue.go
  pkg/pdutil/pd.go
  pkg/restore/batcher.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/restore.go
  run-test.sh
  tests/br_other/run.sh
Labels: needs-cherry-pick-4.0, status/LGT2

#544 *: add errors.toml
  Makefile
  cmd/backup.go
  cmd/restore.go
  errors.toml
  go.mod1
  go.sum1
  pkg/backup/client_test.go
  pkg/cdclog/decoder.go
  pkg/cdclog/decoder_test.go
  pkg/errors/errors.go
  pkg/restore/backoff.go
  pkg/restore/batcher.go
  pkg/restore/batcher_test.go
  pkg/restore/client.go
  pkg/restore/client_test.go
  pkg/restore/db.go
  pkg/restore/db_test.go
  pkg/restore/log_client.go
  pkg/restore/util.go
  pkg/utils/safe_point_test.go
  pkg/utils/schema.go
  tests/br_key_locked/locker.go
  tools/Makefile
  tools/check-errdoc.sh
  tools/go.mod
  tools/go.sum
  tools/go_mod_guard.go
Labels: CanMerge, needs-cherry-pick-4.0, status/LGT2

#555 pd: disable location replacement
  pkg/pdutil/pd.go
  run-test.sh
  tests/br_other/run.sh
  tests/br_tiflash/run.sh
Labels: CanMerge, needs-cherry-pick-4.0, status/LGT2

#562 *: cherry-picking some PRs for v4.0.8
  Makefile
  main.go
  pkg/backup/client.go
  pkg/backup/push.go
  pkg/gluetikv/glue.go
  pkg/pdutil/pd.go
  pkg/restore/batcher.go
  pkg/restore/batcher_test.go
  pkg/restore/client.go
  pkg/restore/client_test.go
  pkg/restore/pipeline_items.go
  pkg/restore/util.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/restore.go
  pkg/task/restore_log.go
  pkg/task/restore_raw.go
  pkg/utils/logging.go
  tests/br_other/run.sh
  tests/br_tiflash/run.sh
Labels: status/LGT2

#563 *: add errors.toml (#544)
  Makefile
  cmd/backup.go
  cmd/restore.go
  errors.toml
  go.mod
  go.mod1
  go.sum1
  pkg/backup/client_test.go
  pkg/cdclog/decoder.go
  pkg/cdclog/decoder_test.go
  pkg/errors/errors.go
  pkg/restore/backoff.go
  pkg/restore/batcher.go
  pkg/restore/batcher_test.go
  pkg/restore/client.go
  pkg/restore/client_test.go
  pkg/restore/db.go
  pkg/restore/db_test.go
  pkg/restore/log_client.go
  pkg/restore/util.go
  pkg/utils/safe_point_test.go
  pkg/utils/schema.go
  tests/br_key_locked/locker.go
  tools/Makefile
  tools/check-errdoc.sh
  tools/go.mod
  tools/go.sum
  tools/go_mod_guard.go
Labels: CanMerge, status/LGT2

#561 progress: removed the progress struct
  pkg/gluetikv/glue.go
  pkg/utils/progress.go
  pkg/utils/progress_test.go
Labels: needs-cherry-pick-4.0, status/LGT2

#568 cdclog: Fix serval bugs about restore cdclog feature.
  cmd/restore.go
  pkg/cdclog/decoder.go
  pkg/cdclog/puller.go
  pkg/restore/log_client.go
  pkg/storage/local.go
Labels: needs-cherry-pick-4.0, status/LGT2

#571 cdclog: Fix serval bugs about restore cdclog feature. (#568)
  cmd/restore.go
  pkg/cdclog/decoder.go
  pkg/cdclog/puller.go
  pkg/restore/log_client.go
  pkg/storage/local.go
Labels: status/LGT2

#569 Spelling error in code comment
  pkg/backup/push.go
  pkg/restore/batcher.go
  pkg/restore/pipeline_items.go
  pkg/restore/split.go
Labels: first-time-contributor, status/LGT2

#572 update uploader with extra options
  pkg/storage/s3.go
Labels: status/LGT2
