Repository pingcap/br, pull requests merged in 2020-06, with the labels that each got.

#327 Add TiFlash test cases
  Makefile
  pkg/conn/conn.go
  pkg/restore/import.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/utils/math.go
  pkg/utils/math_test.go
  tests/README.md
  tests/_utils/make_tiflash_config
  tests/_utils/run_services
  tests/br_rawkv/run.sh
  tests/br_tiflash/run.sh
  tests/config/pd.toml
  tests/download_tools.sh
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0

#331 cherry-pick #327 to 4.0
  Makefile
  pkg/conn/conn.go
  pkg/restore/import.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/utils/math.go
  pkg/utils/math_test.go
  tests/README.md
  tests/_utils/make_tiflash_config
  tests/_utils/run_services
  tests/br_rawkv/run.sh
  tests/br_tiflash/run.sh
  tests/config/pd.toml
  tests/download_tools.sh
Labels: LGT1, cherry-pick

#330 cherry-pick #327 to 3.1
  Makefile
  pkg/conn/conn.go
  pkg/restore/import.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/utils/math.go
  pkg/utils/math_test.go
  tests/README.md
  tests/_utils/make_tiflash_config
  tests/_utils/run_services
  tests/br_rawkv/run.sh
  tests/br_tiflash/run.sh
  tests/config/pd.toml
  tests/download_tools.sh
Labels: LGT1, cherry-pick

#335 *: add version check before start (#311)
  Makefile
  go.mod
  go.sum
  pkg/conn/conn.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: LGT1

#338 cherry-pick #300 to v4.0
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/restore/split_client.go
  tests/br_key_locked/codec.go
Labels: cherry-pick

#334 utils: fix excessive refresh frequency when BR_LOG_TO_TERM=1
  pkg/utils/progress.go
  pkg/utils/progress_test.go
Labels: LGT1, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#339 restore: replace ErrGRPC by recognizing raw gRPC errors
  pkg/restore/backoff.go
  pkg/restore/backoff_test.go
  pkg/restore/import.go
Labels: CanMerge, LGT2, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#313 task: expose table filter for `backup full` and `restore full`
  cmd/backup.go
  cmd/restore.go
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/backup/schema_test.go
  pkg/task/backup.go
  pkg/task/common.go
  pkg/task/restore.go
  tests/br_table_filter/run.sh
Labels: CanMerge, LGT2, needs-cherry-pick-4.0

#201 Fix the issue that rawkv restore's end key is incorrectly inclusive when restoring partial of backed up data
  pkg/restore/import.go
  tests/br_rawkv/client.go
  tests/br_rawkv/run.sh
Labels: LGT1, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#347 Support JSON log (#336)
  cmd/cmd.go
Labels: LGT2, contribution

#346 update tidb version to latest
  go.mod
  go.sum
  pkg/restore/db.go
Labels: LGT1, needs-cherry-pick-4.0

#342 fix version check with hash version
  pkg/restore/client.go
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: LGT1, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#266 Pipelined restore.
  .gitignore
  pkg/restore/batcher.go
  pkg/restore/batcher_test.go
  pkg/restore/client.go
  pkg/restore/pipeline_items.go
  pkg/restore/range.go
  pkg/restore/util.go
  pkg/restore/util_test.go
  pkg/task/restore.go
  tests/br_db_online_newkv/run.sh
  tests/br_small_batch_size/run.sh
  tests/br_small_batch_size/workload
Labels: LGT2, needs-cherry-pick-3.1, needs-cherry-pick-4.0, release-blocker

#349 Fix some issue in qa test
  pkg/restore/import.go
  pkg/task/backup.go
Labels: LGT1, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#356 Cherry-pick Pipelined restore (#266) to 4.0
  .gitignore
  pkg/restore/batcher.go
  pkg/restore/batcher_test.go
  pkg/restore/client.go
  pkg/restore/pipeline_items.go
  pkg/restore/range.go
  pkg/restore/util.go
  pkg/restore/util_test.go
  pkg/task/restore.go
  tests/br_db_online_newkv/run.sh
  tests/br_small_batch_size/run.sh
  tests/br_small_batch_size/workload
Labels: LGT2, cherry-pick

#359 Print keys on log as hex string
  cmd/validate.go
  pkg/backup/client.go
  pkg/restore/import.go
  pkg/restore/range.go
  pkg/restore/split.go
  pkg/restore/util.go
  pkg/rtree/rtree.go
  pkg/utils/logging.go
Labels: CanMerge, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#363 cherry-pick #359 to 4.0
  cmd/validate.go
  pkg/backup/client.go
  pkg/restore/import.go
  pkg/restore/range.go
  pkg/restore/split.go
  pkg/restore/util.go
  pkg/rtree/rtree.go
  pkg/utils/logging.go
Labels: LGT2

#357 Cherry-pick #266 to release-3.1
  .gitignore
  pkg/restore/batcher.go
  pkg/restore/batcher_test.go
  pkg/restore/client.go
  pkg/restore/pipeline_items.go
  pkg/restore/range.go
  pkg/restore/util.go
  pkg/restore/util_test.go
  pkg/task/restore.go
  tests/br_db_online_newkv/run.sh
  tests/br_small_batch_size/run.sh
  tests/br_small_batch_size/workload
Labels: LGT2, cherry-pick

#358 br: add lock file
  pkg/backup/client.go
  pkg/task/backup.go
  pkg/utils/schema.go
  tests/br_other/run.sh
Labels: LGT1, enhancement, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#367 tests: add retry on start services
  tests/_utils/run_services
  tests/br_other/run.sh
  tests/br_tiflash/run.sh
Labels: LGT2, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#362 Update TiDB version to latest
  go.mod
  go.sum
Labels: CanMerge, LGT2

#368 grpc: fix "too many ping" error in pd
  pkg/conn/conn.go
  pkg/restore/client.go
Labels: LGT1, contribution, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#381 main: log the received OS signal
  main.go
Labels: LGT2, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#384 ignore exists table when restore tables
  pkg/backup/client.go
  pkg/gluetikv/glue.go
  pkg/summary/collector.go
  pkg/summary/summary.go
  pkg/task/backup.go
Labels: enhancement, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#388 ignore exists table when restore tables (#384)
  pkg/backup/client.go
  pkg/summary/collector.go
  pkg/summary/summary.go
  pkg/task/backup.go
Labels: cherry-pick

#372 task: allow start pprof at runtime by unix signal
  cmd/cmd.go
  pkg/task/restore.go
  pkg/utils/dyn_pprof_other.go
  pkg/utils/dyn_pprof_unix.go
  pkg/utils/pprof.go
  tests/br_other/run.sh
Labels: LGT2, needs-cherry-pick-3.1, needs-cherry-pick-4.0
