Repository pingcap/br, pull requests merged in 2020-08, with the labels that each got.

#448 brieSQL: fix multi-thread panic during SQL restore
  pkg/task/restore.go
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#449 brieSQL: fix multi-thread panic during SQL restore (#448)
  pkg/task/restore.go
Labels: status/LGT2

#447 Update PD and adapt new PD client APIs
  go.mod
  go.sum
  pkg/restore/split_client.go
  tests/br_key_locked/codec.go
Labels: status/LGT2

#451 backup: support set compression level for sst file
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  tests/br_full/run.sh
Labels: needs-cherry-pick-4.0, status/LGT2

#455 checksum: fix SEGFAULT during backup
  pkg/checksum/executor.go
Labels: CanMerge, bug, status/LGT2

#446 storage: extend the `ExternalStorage` interface and implements
  pkg/storage/gcs.go
  pkg/storage/local.go
  pkg/storage/noop.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
  pkg/utils/math.go
  pkg/utils/math_test.go
Labels: CanMerge, status/LGT2

#456 add s3 api to adapt cdc log
  pkg/storage/gcs.go
  pkg/storage/local.go
  pkg/storage/noop.go
  pkg/storage/parse.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
Labels: 5.0 request, needs-cherry-pick-4.0, status/LGT2, status/WIP

#462 storage: extend the `ExternalStorage` interface and implements (#446)
  pkg/storage/gcs.go
  pkg/storage/local.go
  pkg/storage/noop.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
  pkg/utils/math.go
  pkg/utils/math_test.go
Labels: status/LGT2

#459 storage: use path in WalkDir and Open
  pkg/storage/gcs.go
  pkg/storage/local.go
  pkg/storage/noop.go
  pkg/storage/s3.go
  pkg/storage/storage.go
Labels: needs-cherry-pick-4.0, status/LGT2

#460 tidb_tools: update dependency
  go.mod
  go.sum
Labels: CanMerge, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#461 backup: support set compression level for sst file (#451)
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/backup/client_test.go
  pkg/mock/mock_cluster.go
  pkg/restore/db.go
  pkg/restore/split_client.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/utils/schema.go
  tests/br_full/run.sh
  tests/br_key_locked/codec.go
  tests/br_key_locked/locker.go
Labels: CanMerge, status/LGT2

#466 update tidb / tidb-tools dependencies
  go.mod
  go.sum
Labels: CanMerge, status/LGT2

#463 add s3 api to adapt cdc log (#456)
  go.mod
  go.sum
  pkg/backup/client_test.go
  pkg/mock/mock_cluster.go
  pkg/restore/split_client.go
  pkg/storage/gcs.go
  pkg/storage/local.go
  pkg/storage/noop.go
  pkg/storage/parse.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
  pkg/utils/schema.go
  tests/br_key_locked/codec.go
  tests/br_key_locked/locker.go
Labels: cherry-pick, status/LGT2

#467 storage: update WalkDir
  pkg/storage/gcs.go
  pkg/storage/local.go
  pkg/storage/noop.go
  pkg/storage/s3.go
  pkg/storage/storage.go
Labels: needs-cherry-pick-4.0, status/LGT1

#471 backup: remove duplicate kv size summary collect
  pkg/backup/client.go
Labels: bug, needs-cherry-pick-4.0, status/LGT2

#468 integration_test: fix br_incremental_index test not stable
  pkg/backup/client.go
  pkg/task/backup.go
  tests/br_incremental_index/run.sh
Labels: status/LGT2

#473 restore: switch mode immediately when restore start.
  pkg/restore/client.go
Labels: bug, needs-cherry-pick-4.0, status/LGT1

#481 Fix CI failed with "tikv timeout"
  go.mod
  go.sum
Labels: CanMerge, status/LGT2
