Repository pingcap/br, pull requests merged in 2020-12, with the labels that each got.

#594 test: update coverage
  cmd/restore.go
  pkg/kv/kv_test.go
  pkg/restore/db.go
  pkg/restore/log_client.go
  pkg/restore/log_client_test.go
  pkg/task/restore.go
  tests/br_log_restore/run.sh
Labels: needs-cherry-pick-4.0, status/LGT2

#628 split: add unit test
  pkg/restore/split.go
  pkg/restore/split_test.go
Labels: status/LGT2

#630 add some test contain pkg/task/backup_test and pkg/utils/key_test
  pkg/task/backup_test.go
  pkg/utils/key_test.go
Labels: status/LGT2

#636 pd: add check when leader is empty
  pkg/restore/split.go
  pkg/restore/split_client.go
Labels: status/LGT2

#646 tests: fix br_tls failure and make stop_services more robust
  tests/_utils/run_services
Labels: status/LGT2

#644 pdutil: set max-pending-peer-count to a large value in RemovePdScheduers
  pkg/pdutil/pd.go
  pkg/pdutil/pd_test.go
  tests/br_log_restore/run.sh
  tests/br_other/run.sh
Labels: CanMerge, status/LGT2

#647 gcs: fix wrong path of gcs prefix
  pkg/storage/gcs.go
  pkg/storage/gcs_test.go
  pkg/storage/parse.go
  pkg/storage/parse_test.go
  tests/br_log_restore/run.sh
Labels: needs-cherry-pick-4.0, status/LGT3

#649 go mod: update tidb dependency
  go.mod1
  go.sum1
Labels: status/LGT2

#618 storage: auto retry s3 reader
  pkg/storage/s3.go
  pkg/storage/s3_test.go
Labels: CanMerge, status/LGT2

#653 *: redact log and error messages, add log-redact parameter
  Makefile
  cmd/cmd.go
  pkg/backup/client.go
  pkg/kv/kv.go
  pkg/logutil/logging.go
  pkg/logutil/redact.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/restore/log_client.go
  pkg/restore/pipeline_items.go
  pkg/restore/range.go
  pkg/restore/split.go
  pkg/restore/split_client.go
  pkg/restore/util.go
Labels: status/LGT2

#578 restore: merge small ranges
  cmd/debug.go
  pkg/backup/client.go
  pkg/restore/client.go
  pkg/restore/merge.go
  pkg/restore/merge_test.go
  pkg/restore/util.go
  pkg/restore/util_test.go
  pkg/rtree/rtree.go
  pkg/task/backup_test.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/task/restore_test.go
  tests/_utils/run_services
  tests/br_debug_meta/run.sh
  tests/br_debug_meta/workload
  tests/br_full_ddl/run.sh
  tests/br_other/run.sh
Labels: CanMerge, status/LGT2

#667 test: fix integration partition test
  Makefile
  go.mod1
  go.sum1
  tests/br_table_partition/run.sh
Labels: needs-cherry-pick-5.0, status/LGT1

#657 *: add opentracer in br
  cmd/backup.go
  cmd/restore.go
  go.mod1
  go.sum1
  pkg/backup/client.go
  pkg/backup/push.go
  pkg/backup/schema.go
  pkg/cdclog/puller.go
  pkg/conn/conn.go
  pkg/pdutil/pd.go
  pkg/restore/batcher.go
  pkg/restore/client.go
  pkg/restore/log_client.go
  pkg/restore/split.go
  pkg/storage/s3_test.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/trace/tracing.go
  pkg/trace/tracing_test.go
Labels: status/LGT2

#670 test: fix br_table_partition integration test
  Makefile
  go.mod1
  go.sum1
  tests/br_table_partition/run.sh
Labels: status/LGT1

#664 gcs: fix url parse panic
  pkg/storage/parse.go
  pkg/storage/parse_test.go
Labels: CanMerge, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT2
