Repository pingcap/br, pull requests merged in 2020-04, with the labels that each got.

#221 README of test omitted one third-party dependence.
  tests/README.md
Labels: contribution

#220 Max index length
  pkg/task/restore.go
Labels: contribution

#230 enable tidb config by default
  pkg/task/restore.go
  tests/br_alter_pk_server/run.sh
  tests/br_incompatible_tidb_config/config/tidb.toml
  tests/br_incompatible_tidb_config/config/tikv.toml
  tests/br_incompatible_tidb_config/run.sh
Labels: LGT1

#223 --checksum=false won't work.
  pkg/backup/client.go
  pkg/backup/schema.go
  pkg/restore/client.go
  pkg/task/backup.go
  pkg/task/restore.go
  pkg/utils/math.go
  pkg/utils/math_test.go
  pkg/utils/schema.go
  tests/br_skip_checksum/run.sh
  tests/br_skip_checksum/workload
Labels: LGT2, enhancement

#233 fill size in SSTMeta
  pkg/restore/util.go
Labels: LGT1

#231 Use table info
  pkg/restore/db.go
  pkg/task/restore.go
  tests/br_incompatible_tidb_config/run.sh
Labels: enhancement

#236 cmd: don't use ':' in the default log file name
  cmd/cmd.go
Labels: LGT1

#239 README: update build status badge
  README.md
Labels: LGT1

#244 tools: replace retool by GO111MODULE
  CONTRIBUTING.md
  Makefile
  README.md
  tools.json
  tools/.gitignore
  tools/Makefile
  tools/go.mod
  tools/go.sum
  tools/go_mod_guard.go
Labels: LGT2

#243 pass sse_kms_key_id to S3
  .gitignore
  go.mod
  go.sum
  pkg/storage/s3.go
Labels: LGT2

#240 Restore with lower case
  go.mod
  go.sum
  tests/br_case_sensitive/run.sh
Labels: LGT1

#246 storage: support placing the S3/GCS options into the storage URL
  pkg/storage/parse.go
  pkg/storage/parse_test.go
  tests/br_s3/run.sh
Labels: LGT2

#245 Restore with lower case (#240)
  CONTRIBUTING.md
  Makefile
  README.md
  go.mod
  go.sum
  tests/br_case_sensitive/run.sh
  tools.json
  tools/.gitignore
  tools/Makefile
  tools/go.mod
  tools/go.sum
  tools/go_mod_guard.go
Labels: LGT2

#248 Rebase auto random counter after restore
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/restore/db.go
  tests/br_incompatible_tidb_config/run.sh
  tests/br_key_locked/locker.go
  tools/go.sum
Labels: LGT1

#249 glue,task: let the tasks inform the glue about the BackupTS and Size.
  pkg/backup/client.go
  pkg/glue/glue.go
  pkg/gluetidb/glue.go
  pkg/gluetikv/glue.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/utils/schema.go
Labels: LGT2

#237 add some design docs.
  docs/cn/2019-08-05-new-design-of-backup-restore.md
  docs/cn/2019-09-09-BR-key-rewrite-disscussion.md
  docs/cn/2019-09-17-design-of-reorganize-importSST-to-TiKV.md
  docs/resources/arch-of-reorganized-importer.svg
  docs/resources/download-sst-diagram.svg
  docs/resources/solution3-of-key-rewrite.svg
Labels: LGT1

#253 fix ci for release-3.1
  go.sum
Labels: LGT1
