Repository pingcap/br, pull requests merged in 2020-05, with the labels that each got.

#257 Backup: register backupTS as safepoint to PD
  pkg/backup/client.go
  pkg/backup/safe_point.go
  pkg/backup/safe_point_test.go
  pkg/task/backup.go
  tests/br_z_gc_safepoint/gc.go
  tests/br_z_gc_safepoint/run.sh
Labels: enhancement

#261 pass sse_kms_key_id to S3 (#243)
  .gitignore
  go.mod
  go.sum
  pkg/storage/s3.go
Labels: backport/release-3.1

#263 .github: change the PR template to include the "Release note" section
  .github/pull_request_template.md
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0

#262 *: fix lints
  Makefile
  cmd/cmd.go
  cmd/restore.go
  pkg/backup/client.go
  pkg/backup/safe_point.go
  pkg/backup/schema.go
  pkg/checksum/executor.go
  pkg/conn/conn.go
  pkg/gluetidb/glue.go
  pkg/gluetikv/glue.go
  pkg/mock/mock_cluster.go
  pkg/restore/client.go
  pkg/restore/db.go
  pkg/restore/import.go
  pkg/restore/range.go
  pkg/restore/split.go
  pkg/restore/util.go
  pkg/rtree/rtree.go
  pkg/storage/gcs.go
  pkg/storage/local.go
  pkg/storage/noop.go
  pkg/storage/parse_test.go
  pkg/storage/s3.go
  pkg/storage/storage.go
  pkg/summary/collector.go
  pkg/summary/summary.go
  pkg/task/backup.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/utils/key.go
  pkg/utils/pd.go
  pkg/utils/progress.go
  pkg/utils/retry.go
  pkg/utils/schema.go
  pkg/utils/version.go
  pkg/utils/worker.go
Labels: LGT1

#272 go.mod: update dependencies
  Makefile
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/backup/client_test.go
  pkg/backup/metrics.go
  pkg/backup/safe_point_test.go
  pkg/backup/schema.go
  pkg/backup/schema_test.go
  pkg/checksum/executor.go
  pkg/checksum/executor_test.go
  pkg/mock/mock_cluster_test.go
  pkg/restore/backoff.go
  pkg/restore/backoff_test.go
  pkg/restore/client.go
  pkg/restore/client_test.go
  pkg/restore/db.go
  pkg/restore/db_test.go
  pkg/restore/import.go
  pkg/restore/range.go
  pkg/restore/range_test.go
  pkg/restore/split.go
  pkg/restore/split_client.go
  pkg/restore/split_test.go
  pkg/restore/util.go
  pkg/restore/util_test.go
  pkg/rtree/rtree_test.go
  pkg/storage/gcs.go
  pkg/storage/gcs_test.go
  pkg/storage/local.go
  pkg/storage/parse_test.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
  pkg/summary/collector.go
  pkg/utils/key_test.go
  pkg/utils/progress.go
  pkg/utils/retry.go
  pkg/utils/unit.go
  pkg/utils/worker.go
  tools/go.mod
  tools/go.sum
Labels: LGT2, needs-cherry-pick-4.0

#273 Rebase auto random counter after restore (#248)
  go.mod
  go.sum
  main_test.go
  pkg/backup/client.go
  pkg/restore/db.go
  tests/br_incompatible_tidb_config/run.sh
Labels: LGT2, cherry-pick

#247 add retry on split client.
  Makefile
  go.mod
  go.sum
  pkg/restore/split_client.go
  tests/br_split_region_fail/run.sh
  tests/br_split_region_fail/workload
  tools/Makefile
  tools/go.mod
  tools/go.sum
  tools/go_mod_guard.go
Labels: LGT2, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#270 summary: fix restore files count miss
  pkg/summary/collector.go
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0

#279 update tidbtools
  go.mod
  go.sum
Labels: LGT2, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#283 cherry-pick #247 to relase 4.0
  Makefile
  go.mod
  go.sum
  pkg/restore/split_client.go
  tests/br_split_region_fail/run.sh
  tests/br_split_region_fail/workload
  tools/Makefile
  tools/go.mod
  tools/go.sum
  tools/go_mod_guard.go
Labels: LGT1

#284 cherry-pick #279 to release 4.0
  go.mod
  go.sum
Labels: LGT2, cherry-pick

#276 restore: set lower bound of batch size
  pkg/task/restore.go
Labels: LGT1, LGT2, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#288 tests: wait tikv 100 seconds to init
  tests/_utils/run_services
Labels: LGT1, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#292 Don't log secret of s3.
  cmd/backup.go
  cmd/restore.go
  cmd/validate.go
  pkg/backup/client.go
  pkg/task/common.go
  pkg/task/common_test.go
  pkg/utils/version.go
  tests/br_s3/run.sh
Labels: LGT1, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#294 change auto_random columns to bigint.
  tests/br_incompatible_tidb_config/run.sh
Labels: LGT1, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#214 restore: use cached InfoSchema rather than always fetching from store
  pkg/restore/client.go
  tests/br_300_small_tables/run.sh
Labels: CanMerge, LGT2

#303 cherry-pick #247 to 3.1
  Makefile
  go.mod
  go.sum
  pkg/restore/split_client.go
  tests/br_split_region_fail/run.sh
  tests/br_split_region_fail/workload
  tools/Makefile
  tools/go.mod
  tools/go.sum
  tools/go_mod_guard.go
Labels: cherry-pick

#242 Support backup & restore views and sequences
  pkg/backup/client.go
  pkg/restore/db.go
  tests/br_views_and_sequences/run.sh
  tests/download_tools.sh
Labels: CanMerge, LGT2, needs-cherry-pick-4.0

#298 restore: Make all download error as retryable
  pkg/restore/backoff.go
  pkg/restore/backoff_test.go
  pkg/restore/import.go
  pkg/utils/retry.go
Labels: CanMerge, LGT2, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#278 restore: adjust PD config to speed up restore (#198)
  docker/config/pd.toml
  pkg/conn/conn.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
Labels: CanMerge, LGT2, cherry-pick

#306 Support backup & restore views and sequences (#242)
  pkg/backup/client.go
  pkg/restore/db.go
  tests/br_views_and_sequences/run.sh
  tests/download_tools.sh
Labels: LGT1, cherry-pick

#287 conn: attach context to pd client
  pkg/conn/conn.go
Labels: CanMerge, LGT1

#317 restore: support restore empty databases and tables
  pkg/task/restore.go
  tests/br_backup_empty/run.sh
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0

#315 Fix row data lost
  pkg/restore/import.go
  pkg/restore/util.go
  pkg/restore/util_test.go
  tests/br_range/run.sh
Labels: LGT1, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#316 fix typo in cmd/cmd.go
  cmd/cmd.go
Labels: CanMerge, LGT1, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#310 tasks: print error to log after fail.
  cmd/backup.go
  cmd/restore.go
Labels: LGT2, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#311 *: add version check before start
  Makefile
  go.mod
  pkg/conn/conn.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: LGT1, enhancement, needs-cherry-pick-3.1, needs-cherry-pick-4.0

#285 cherry-pick #279 to release-3.1
  go.mod
  go.sum
Labels: LGT1

#314 [3.1] restore: Make all download error as retryable (#298)
  pkg/restore/backoff.go
  pkg/restore/backoff_test.go
  pkg/restore/import.go
  pkg/utils/retry.go
Labels: CanMerge, LGT1, cherry-pick
