Repository pingcap/br, pull requests merged in 2020-02, with the labels that each got.

#148 Fixed handling for a dbName that do not exist in the backup being restored
  cmd/restore.go
Labels: LGT2

#156 *: extracts runBackup/runRestore in cmd into pkg/task
  cmd/backup.go
  cmd/cmd.go
  cmd/restore.go
  cmd/validate.go
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/backup/client_test.go
  pkg/backup/schema_test.go
  pkg/restore/db_test.go
  pkg/restore/util.go
  pkg/storage/flags.go
  pkg/storage/gcs.go
  pkg/storage/gcs_test.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
  pkg/task/backup.go
  pkg/task/common.go
  pkg/task/restore.go
Labels: LGT2, enhancement

#150 restore: fix restore summary log
  pkg/restore/client.go
Labels: LGT1

#158 Reduce TiDB dependencies
  cmd/backup.go
  cmd/cmd.go
  cmd/restore.go
  pkg/backup/safe_point_test.go
  pkg/backup/schema_test.go
  pkg/checksum/executor_test.go
  pkg/conn/conn.go
  pkg/glue/glue.go
  pkg/gluetidb/glue.go
  pkg/mock/mock_cluster.go
  pkg/mock/mock_cluster_test.go
  pkg/restore/backoff_test.go
  pkg/restore/client.go
  pkg/restore/client_test.go
  pkg/restore/db.go
  pkg/restore/db_test.go
  pkg/restore/util.go
  pkg/task/backup.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/utils/mock_cluster_test.go
  pkg/utils/schema.go
Labels: LGT2, enhancement
