Repository pingcap/br, pull requests merged in 2020-09, with the labels that each got.

#469 cherry-pick #467 to release-4.0
  pkg/storage/gcs.go
  pkg/storage/local.go
  pkg/storage/noop.go
  pkg/storage/s3.go
  pkg/storage/storage.go
Labels: status/LGT2

#480 summary: add real time cost to log collector
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/summary/collector.go
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#483 *: don't remove tiflash more.
  cmd/restore.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/restore/pipeline_items.go
  pkg/restore/util.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/utils/pd.go
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#476 storage: support s3 seek end
  pkg/storage/s3.go
  pkg/storage/s3_test.go
Labels: needs-cherry-pick-4.0, status/LGT2

#488 update tidb-tools/pd dependencies
  cmd/validate.go
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/backup/client_test.go
  pkg/backup/safe_point.go
  pkg/backup/safe_point_test.go
  pkg/conn/conn.go
  pkg/conn/conn_test.go
  pkg/glue/glue.go
  pkg/gluetidb/glue.go
  pkg/gluetikv/glue.go
  pkg/mock/mock_cluster.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/restore/split_client.go
  pkg/restore/split_test.go
  pkg/task/common.go
  pkg/utils/pd.go
  pkg/utils/version.go
  pkg/utils/version_test.go
  tests/br_key_locked/codec.go
  tests/br_key_locked/locker.go
  tests/br_z_gc_safepoint/gc.go
Labels: status/LGT1

#490 *: update tidb dependencies
  go.mod
  go.sum
Labels: status/LGT1

#492 storage: fix walk dir file size
  pkg/storage/local.go
  pkg/storage/local_test.go
Labels: needs-cherry-pick-4.0, status/LGT2

#493 backup,restore: fix panic when pd.GetRegion return nil
  pkg/backup/client.go
  pkg/restore/import.go
Labels: status/LGT2

#503 pkg: remove config about AllowsExpressionIndex
  pkg/task/restore.go
Labels: 5.0 request, status/LGT1

#505 error: record store id when backup connection failed
  pkg/backup/client.go
Labels: status/LGT2

#500 *: fix the tiflash test failure
  tests/_utils/run_services
  tests/br_tiflash/run.sh
  tests/config/tikv.toml
Labels: CanMerge, needs-cherry-pick-4.0, status/LGT2

#487 [cherry-pick] *: don't remove tiflash more.(#483)
  cmd/restore.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/restore/pipeline_items.go
  pkg/restore/util.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/utils/pd.go
  pkg/utils/version.go
  pkg/utils/version_test.go
Labels: CanMerge, cherry-pick, status/LGT2

#502 .editorconfig: add .editorconfig file, make tab_size = 4
  .editorconfig
Labels: CanMerge, status/LGT2

#509 restore: restore tidb config after restoring
  pkg/task/common_test.go
  pkg/task/restore.go
  tests/br_db/run.sh
  tests/br_full/run.sh
Labels: CanMerge, needs-cherry-pick-4.0, status/LGT2

#513 [cherry-pick] restore: restore tidb config after restoring(#509)
  pkg/task/common_test.go
  pkg/task/restore.go
  tests/br_db/run.sh
  tests/br_full/run.sh
Labels: cherry-pick, status/LGT2

#514 remove useless code
  pkg/backup/client.go
Labels: CanMerge, contribution, needs-cherry-pick-4.0, status/LGT2

#512 *: move lightning code into br
  pkg/cdclog/decoder.go
  pkg/cdclog/decoder_test.go
  pkg/cdclog/session.go
  pkg/cdclog/session_test.go
  pkg/manual/manual.go
  pkg/manual/manual_nocgo.go
  pkg/utils/bytes.go
  pkg/utils/checksum.go
  pkg/utils/checksum_test.go
Labels: status/LGT2

#515 log: optimize some log
  pkg/backup/client.go
  pkg/checksum/executor.go
  pkg/restore/util.go
Labels: CanMerge, needs-cherry-pick-4.0, status/LGT2

#452 *: remove in-struct context
  pkg/backup/client.go
  pkg/backup/push.go
  pkg/restore/client.go
  pkg/restore/client_test.go
  pkg/restore/pipeline_items.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
Labels: CanMerge, status/LGT3

#521 go.mod: update parser and tidb
  go.mod
  go.sum
Labels: release-blocker, status/LGT2

#508 backup: add retry when tikv is down
  pkg/backup/client.go
  pkg/backup/push.go
  pkg/conn/conn.go
  tests/br_full/run.sh
Labels: needs-cherry-pick-4.0, status/LGT2

#525 pkg: make TiDB not dependent on gcc
  pkg/manual/manual.go
  pkg/manual/manual_nocgo.go
Labels: status/LGT2

#523 [cherry-pick] backup: add retry when tikv is down (#508)
  pkg/backup/client.go
  pkg/backup/push.go
  pkg/conn/conn.go
  tests/br_full/run.sh
Labels: status/LGT2

#482 Restore: support restore data from cdc log
  cmd/restore.go
  go.mod
  go.sum
  pkg/cdclog/buffer.go
  pkg/cdclog/puller.go
  pkg/kv/checksum.go
  pkg/kv/checksum_test.go
  pkg/kv/kv.go
  pkg/kv/session.go
  pkg/kv/session_test.go
  pkg/restore/import.go
  pkg/restore/log_client.go
  pkg/restore/split.go
  pkg/restore/util.go
  pkg/restore/util_test.go
  pkg/storage/local.go
  pkg/task/restore_log.go
Labels: 5.0 request, status/LGT1

#524 Writer like interface (with context) on top of Uploader
  pkg/storage/local.go
  pkg/storage/storage.go
  pkg/storage/writer.go
  pkg/storage/writer_test.go
Labels: contribution, status/LGT1

#527 URI() method to see the base URI of an ExternalStorage
  pkg/storage/gcs.go
  pkg/storage/gcs_test.go
  pkg/storage/local.go
  pkg/storage/noop.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
Labels: contribution, status/LGT1

#531 adjust rawURL to local path if no u.Schema is given
  pkg/storage/parse.go
  pkg/storage/parse_test.go
Labels: status/LGT1

#535 raw_restore: set concurrency to default when no config here
  pkg/task/restore_raw.go
  tests/br_rawkv/run.sh
Labels: CanMerge, status/LGT2

#530 validate: manual reset pd config back
  cmd/validate.go
  pkg/conn/scheduler_utils.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_log.go
  pkg/task/restore_raw.go
  tests/br_other/run.sh
Labels: CanMerge, status/LGT2

#526 restore: not use `MaxInt64` to read data
  pkg/restore/client_test.go
Labels: CanMerge, needs-cherry-pick-4.0, status/LGT2

#532 move pd scheduler to separated pkg
  cmd/validate.go
  pkg/backup/client_test.go
  pkg/conn/conn.go
  pkg/conn/conn_test.go
  pkg/conn/scheduler_utils.go
  pkg/pdutil/pd.go
  pkg/pdutil/pd_test.go
Labels: status/LGT2

#475 *: initial effort to support error code
  Makefile
  cmd/validate.go
  go.mod
  go.sum
  main.go
  pkg/backup/client.go
  pkg/backup/client_test.go
  pkg/backup/push.go
  pkg/backup/safe_point.go
  pkg/backup/safe_point_test.go
  pkg/cdclog/decoder.go
  pkg/conn/conn.go
  pkg/errors/errors.go
  pkg/pdutil/pd.go
  pkg/restore/backoff.go
  pkg/restore/backoff_test.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/restore/log_client.go
  pkg/restore/range.go
  pkg/restore/range_test.go
  pkg/restore/split.go
  pkg/restore/split_client.go
  pkg/restore/util.go
  pkg/restore/util_test.go
  pkg/storage/gcs.go
  pkg/storage/gcs_test.go
  pkg/storage/parse.go
  pkg/storage/parse_test.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/utils/key.go
  pkg/utils/key_test.go
  pkg/utils/pd.go
  pkg/utils/version.go
  pkg/utils/version_test.go
  tests/_utils/run_br
  tests/_utils/run_services
  tests/br_full_ddl/run.sh
  tests/br_full_index/run.sh
  tests/br_history/run.sh
  tests/br_tls/run.sh
  tests/config/.gitignore
  tests/run.sh
Labels: status/LGT2

#528 test: add integration test for log restore
  Makefile
  pkg/cdclog/buffer.go
  pkg/restore/log_client.go
  pkg/storage/s3.go
  tests/README.md
  tests/br_log_restore/run.sh
  tests/br_log_restore/workload
  tests/download_tools.sh
Labels: 5.0 request, CanMerge, needs-cherry-pick-4.0, status/LGT2

#519 cmd: extend decode cmd to print any field
  cmd/cmd.go
  cmd/debug.go
  main.go
  tests/br_other/run.sh
Labels: status/LGT2

#545 conn,task: add config about keepalive
  cmd/debug.go
  pkg/conn/conn.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_log.go
  pkg/task/restore_raw.go
Labels: status/LGT2

#541 move pd scheduler to separated pkg (#532)
  pkg/backup/client_test.go
  pkg/conn/conn.go
  pkg/conn/conn_test.go
  pkg/conn/scheduler_utils.go
  pkg/pdutil/pd.go
  pkg/pdutil/pd_test.go
Labels: CanMerge, status/LGT2
