Repository pingcap/br, pull requests merged in 2020-07, with the labels that each got.

#392 readme: update links
  README.md
Labels: LGT2, status/LGT1

#377 Speed up DDL execution by send DDL concurrently
  pkg/restore/client.go
  pkg/restore/util.go
  pkg/task/restore.go
  pkg/utils/worker.go
Labels: status/LGT2

#396 *: run BackupRanges in parallel, change meaning of backup concurrency
  go.mod
  pkg/backup/client.go
  pkg/backup/schema.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/utils/worker.go
Labels: CanMerge, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT3

#371 Cherry-pick #367 and #358 to 3.1
  pkg/backup/client.go
  pkg/task/backup.go
  pkg/utils/schema.go
  tests/_utils/run_services
  tests/br_other/run.sh
  tests/br_tiflash/run.sh
Labels: CanMerge, cherry-pick, status/LGT2

#400 utils: add errors.Annotate on semver errors
  pkg/utils/version.go
Labels: CanMerge, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#402 Set safe point at background
  pkg/backup/client.go
  pkg/backup/safe_point.go
  pkg/task/backup.go
Labels: CanMerge, status/LGT2

#410 cherry pick #402 and #396 to release 4.0.
  go.mod
  pkg/backup/client.go
  pkg/backup/safe_point.go
  pkg/backup/schema.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/utils/worker.go
Labels: status/LGT2

#404 backup: support explicitly set sst compression type
  cmd/backup.go
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
Labels: status/LGT2

#393 task: expose table filter for `backup full` and `restore full` (#313)
  cmd/backup.go
  cmd/restore.go
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/backup/schema_test.go
  pkg/task/backup.go
  pkg/task/common.go
  pkg/task/restore.go
  tests/br_table_filter/run.sh
Labels: CanMerge, cherry-pick, status/LGT2

#413 cherry-pick (#377) to release-4.0
  pkg/restore/client.go
  pkg/restore/util.go
  pkg/task/restore.go
  pkg/utils/worker.go
Labels: cherry-pick, status/LGT2

#420 restore: don't restore auto id if the table doesn't has it.
  pkg/backup/client.go
  pkg/restore/db.go
  pkg/utils/schema.go
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#405 Fix the problem that backup time may be negative
  pkg/backup/client.go
Labels: CanMerge, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#417 Automatic switch mode
  go.mod
  go.sum
  pkg/restore/client.go
  pkg/restore/db_test.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#421 glue: set no register itself to dashboard
  cmd/cmd.go
  pkg/gluetidb/glue.go
  pkg/restore/client_test.go
  pkg/restore/db_test.go
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#406 glue: set query DDL when executing DDLs
  pkg/gluetidb/glue.go
  tests/br_db/run.sh
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#422 cherry-pick #404, #405, #406 and #421 to release 4.0
  cmd/backup.go
  cmd/cmd.go
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/gluetidb/glue.go
  pkg/restore/client_test.go
  pkg/restore/db_test.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  tests/br_db/run.sh
Labels: cherry-pick, status/LGT2

#423 Automatic switch mode (#417)
  go.sum
  pkg/restore/client.go
  pkg/restore/db_test.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
Labels: status/LGT2

#424 remove auto_random option (#343)
  pkg/task/restore.go
Labels: status/LGT1, status/LGT2

#425 update tidb to latest release-4.0
  go.mod
  go.sum
Labels: status/LGT2

#418 backup: move some non-fatal error log into warn level
  pkg/backup/push.go
  pkg/backup/safe_point.go
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#401 task: expose table filter for `backup full` and `restore full` (#313)
  cmd/backup.go
  cmd/restore.go
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/backup/schema_test.go
  pkg/task/backup.go
  pkg/task/common.go
  pkg/task/restore.go
  tests/br_table_filter/run.sh
Labels: cherry-pick, status/LGT2

#426 Remove scheduler
  pkg/conn/scheduler_utils.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/utils/pd.go
  tests/br_other/run.sh
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#399 Add a hint when running on incompatible cluster
  pkg/conn/conn.go
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#411 Refactor: replace wait groups with errgroup, and drop db when test finished
  pkg/backup/schema.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/utils/worker.go
  tests/br_backup_empty/run.sh
  tests/br_small_batch_size/run.sh
  tests/br_split_region_fail/run.sh
  tests/br_tiflash/run.sh
  tests/br_views_and_sequences/run.sh
  tests/br_z_gc_safepoint/run.sh
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#416 fix some design of safe point keeper
  pkg/backup/safe_point.go
  pkg/task/backup.go
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT2

#431 [cherry-pick] remove scheduler(#426)
  pkg/conn/scheduler_utils.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/utils/pd.go
  tests/br_other/run.sh
Labels: CanMerge, cherry-pick, status/LGT2

#432 conn: set PD timeout to 10 secs
  go.mod
  go.sum
  pkg/conn/conn.go
Labels: CanMerge, status/LGT2

#437 backup: set gcttl to 5m if gcttl not set in TiDB
  pkg/backup/client.go
Labels: bug, needs-cherry-pick-3.1, needs-cherry-pick-4.0, release-blocker, status/LGT2

#439 [cherry-pick] fix some design of safe point keeper(#416)
  pkg/backup/safe_point.go
  pkg/task/backup.go
Labels: cherry-pick, status/LGT2

#443 common: adjust config in task RunBackup/RunRestore
  pkg/task/backup.go
  pkg/task/restore.go
Labels: needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/LGT1
