Repository pingcap/br, pull requests merged in 2020-11, with the labels that each got.

#567 restore: set configed keepalive for restore
  pkg/restore/client.go
  pkg/restore/client_test.go
  pkg/restore/import.go
  pkg/restore/log_client.go
  pkg/task/restore.go
  pkg/task/restore_log.go
  pkg/task/restore_raw.go
Labels: status/LGT1

#560 fix: backup will skip empty databases.
  pkg/backup/client.go
  pkg/task/backup.go
Labels: first-time-contributor, status/LGT2

#575 go.mod,tests: update tidb deps and add list partition test case
  Makefile
  go.mod1
  go.sum1
  pkg/kv/session.go
  tests/br_table_partition/prepare.sh
  tests/br_table_partition/run.sh
Labels: CanMerge, status/LGT2

#583 storage: increase aws maxRetries request config from 3 to 6
  pkg/storage/s3.go
Labels: status/LGT2

#587 checksum: correct spelling mistake
  pkg/kv/checksum_test.go
Labels: CanMerge, status/LGT2

#579 cmd,task: disable stray command line args, and log the command in LogArguments
  cmd/backup.go
  cmd/debug.go
  cmd/restore.go
  pkg/task/common.go
Labels: needs-cherry-pick-4.0, status/LGT1

#573 cdclog: Fix bugs and add tests for cdclog feature
  pkg/cdclog/buffer.go
  pkg/cdclog/decoder.go
  pkg/cdclog/decoder_test.go
  pkg/restore/log_client.go
  pkg/restore/log_client_test.go
  tests/br_log_restore/run.sh
Labels: 5.0 request, needs-cherry-pick-4.0, status/LGT2

#589 CI: remove unecessary coverage
  .codecov.yml
Labels: status/LGT2

#593 Update the errors/parser dependence to the latest version
  errors.toml
  go.mod1
  go.sum1
  tools/go.mod
  tools/go.sum
Labels: status/LGT1

#566 add uploader compress writer
  Makefile
  pkg/storage/writer.go
  pkg/storage/writer_test.go
Labels: status/LGT1

#592 pdutil: use temp pause config
  cmd/debug.go
  pkg/pdutil/pd.go
  pkg/pdutil/pd_test.go
  tests/br_full_ddl/run.sh
Labels: needs-cherry-pick-4.0, status/LGT2

#602 summary/: export new log collector
  pkg/gluetikv/glue.go
  pkg/summary/collector.go
  pkg/summary/collector_test.go
  pkg/utils/progress.go
  pkg/utils/progress_test.go
Labels: needs-cherry-pick-4.0, status/LGT2

#601 restore: update the PD and TiDB versions
  go.mod1
  go.sum1
  pkg/restore/db_test.go
Labels: CanMerge, status/LGT2

#610 *: reduce unnecessary error stack trace
  cmd/debug.go
  docker-compose.yaml
  pkg/backup/client.go
  pkg/conn/conn.go
  pkg/logutil/logging.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/restore/range.go
  pkg/restore/split.go
  pkg/restore/util.go
  pkg/rtree/rtree.go
Labels: needs-cherry-pick-4.0, status/LGT2

#614 storage/: handle special character in URL
  pkg/storage/parse.go
  pkg/storage/parse_test.go
  tests/br_s3/run.sh
Labels: status/LGT2

#612 restore: add a new interface for SplitClient to return the original region in BatchSplitRegions
  pkg/restore/split_client.go
  pkg/restore/split_test.go
Labels: status/LGT1

#605 analyze: analyze table after restore
  cmd/backup.go
  cmd/restore.go
  go.mod1
  go.sum1
  pkg/backup/client.go
  pkg/backup/schema_test.go
  pkg/conn/conn.go
  pkg/gluetidb/glue.go
  pkg/restore/batcher_test.go
  pkg/restore/client.go
  pkg/task/backup.go
  pkg/utils/schema.go
  pkg/utils/schema_test.go
  tests/br_full_ddl/run.sh
  tests/br_full_index/run.sh
Labels: CanMerge, needs-cherry-pick-4.0, status/LGT2

#620 pd: fix parse version
  pkg/pdutil/pd.go
  pkg/pdutil/pd_test.go
Labels: CanMerge, needs-cherry-pick-4.0, status/LGT2

#576 restore: change batch size
  pkg/restore/import.go
  pkg/restore/split.go
  pkg/task/restore.go
  tests/br_full_ddl/run.sh
  tests/br_tiflash/run.sh
Labels: needs-cherry-pick-4.0, status/LGT2

#622 cherry-pick important features to release-4.0 branch
  cmd/backup.go
  cmd/debug.go
  cmd/restore.go
  docker-compose.yaml
  go.mod
  go.mod1
  go.sum1
  pkg/backup/client.go
  pkg/backup/client_test.go
  pkg/backup/schema_test.go
  pkg/conn/conn.go
  pkg/gluetidb/glue.go
  pkg/kv/kv.go
  pkg/kv/session.go
  pkg/logutil/logging.go
  pkg/mock/mock_cluster.go
  pkg/restore/batcher_test.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/restore/range.go
  pkg/restore/split.go
  pkg/restore/split_client.go
  pkg/restore/util.go
  pkg/rtree/rtree.go
  pkg/task/backup.go
  pkg/utils/schema.go
  pkg/utils/schema_test.go
  tests/br_full_ddl/run.sh
  tests/br_full_index/run.sh
  tests/br_key_locked/codec.go
  tests/br_key_locked/locker.go
Labels: status/LGT2

#615 backup/: retry for read index not ready and proposal in merging mode
  go.mod1
  go.sum1
  pkg/backup/client.go
  pkg/backup/client_test.go
Labels: needs-cherry-pick-4.0, status/LGT2

#625 *: use errcode-gen in new location
  Makefile
  errors.toml
  go.mod1
  go.sum1
  tools/Makefile
  tools/go.mod
  tools/go.sum
  tools/go_mod_guard.go
Labels: CanMerge, needs-cherry-pick-4.0, status/LGT2

#616 go.mod: update the TiDB and PD client to fix the tso process freeze bug
  go.mod1
  go.sum1
Labels: CanMerge, status/LGT2
