Repository pingcap/br, pull requests merged in 2020-03, with the labels that each got.

#101 backup: add raw backup command
  Makefile
  cmd/backup.go
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/conn/conn.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/utils/key.go
  pkg/utils/key_test.go
  tests/br_rawkv/client.go
  tests/br_rawkv/run.sh
Labels: LGT1, enhancement

#179 restore: speed up retry on not leader
  .codecov.yml
  pkg/restore/backoff.go
  pkg/restore/import.go
  tests/_utils/run_services
  tests/br_table_partition/run.sh
Labels: LGT1

#165 conn, restore: paginate scan regions
  pkg/conn/conn.go
  pkg/restore/import.go
  pkg/restore/split.go
  pkg/restore/split_test.go
  pkg/restore/util.go
  pkg/restore/util_test.go
  tests/_utils/run_services
Labels: LGT2

#167 Batch restore
  cmd/validate.go
  pkg/backup/client.go
  pkg/backup/push.go
  pkg/restore/client.go
  pkg/restore/range.go
  pkg/restore/range_test.go
  pkg/restore/split.go
  pkg/restore/split_test.go
  pkg/restore/util.go
  pkg/rtree/check.go
  pkg/rtree/rtree.go
  pkg/rtree/rtree_test.go
  pkg/summary/collector.go
  pkg/summary/collector_test.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
Labels: LGT1

#181 README, docker: add quick start
  .dockerignore
  .gitignore
  README.md
  cmd/cmd.go
  docker-compose.yaml
  docker/Dockerfile
  docker/config/pd.toml
  docker/config/tidb.toml
  docker/config/tikv.toml
Labels: LGT1

#176 *: update tidb dependency build with go1.14
  Makefile
  cmd/backup.go
  cmd/restore.go
  cmd/validate.go
  go.mod
  go.sum
  main.go
  pkg/restore/util.go
  pkg/storage/parse_test.go
  pkg/storage/s3_test.go
Labels: enhancement

#185 conn: support not shutting down the storage when closing the connection
  pkg/conn/conn.go
  pkg/glue/glue.go
  pkg/gluetidb/glue.go
Labels: LGT1

#186 conn: use GetDomain to avoid some TiDB breaking changes
  cmd/backup.go
  cmd/restore.go
  pkg/conn/conn.go
  pkg/glue/glue.go
  pkg/gluetidb/glue.go
  pkg/utils/progress.go
Labels: LGT2

#175 fix check safepoint & unhide experimental features
  cmd/backup.go
  pkg/backup/client.go
  pkg/storage/gcs.go
  pkg/storage/s3.go
  pkg/task/backup.go
  pkg/task/restore.go
  tests/br_z_gc_safepoint/run.sh
Labels: LGT2

#184 *: update pd deps to v4
  cmd/validate.go
  go.mod
  go.sum
  pkg/backup/client.go
  pkg/backup/safe_point.go
  pkg/backup/safe_point_test.go
  pkg/conn/conn.go
  pkg/conn/conn_test.go
  pkg/glue/glue.go
  pkg/gluetidb/glue.go
  pkg/mock/mock_cluster.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/restore/split_client.go
  pkg/restore/split_test.go
  pkg/task/common.go
  tests/br_key_locked/codec.go
  tests/br_key_locked/locker.go
  tests/br_z_gc_safepoint/gc.go
Labels: LGT1

#140 metrics: add grafana scripts
  metrics/grafana/br.json
Labels: LGT2

#187 filter out all TiFlash nodes when retrieving lists of stores from PD
  pkg/backup/client.go
  pkg/conn/conn.go
  pkg/conn/conn_test.go
  pkg/restore/client.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
Labels: LGT2

#174 Create integration test for S3 storage
  Makefile
  tests/README.md
  tests/_utils/run_services
  tests/br_s3/run.sh
  tests/br_s3/workload
  tests/download_tools.sh
  tests/run.sh
Labels: CanMerge, LGT2

#104 Implement Raw Restore
  cmd/backup.go
  cmd/restore.go
  pkg/gluetidb/glue.go
  pkg/gluetikv/glue.go
  pkg/restore/client.go
  pkg/restore/db.go
  pkg/restore/import.go
  pkg/task/backup_raw.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/utils/key.go
  pkg/utils/key_test.go
  tests/br_rawkv/run.sh
Labels: CanMerge

#197 summary: put summary log at last
  pkg/restore/db.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
Labels: LGT2

#196 *: abstract the progress channel (updateCh) into the glue package
  pkg/backup/client.go
  pkg/backup/push.go
  pkg/backup/schema.go
  pkg/backup/schema_test.go
  pkg/glue/glue.go
  pkg/gluetidb/glue.go
  pkg/gluetikv/glue.go
  pkg/restore/client.go
  pkg/restore/util.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
Labels: LGT2

#189 *: refline logs
  cmd/cmd.go
  pkg/summary/collector.go
Labels: contribution

#202 *: add S3 quick start and few enhancement of log
  README.md
  cmd/cmd.go
  docker-compose.yaml
  docker/Dockerfile
  docker/minio.env
  pkg/summary/collector.go
  pkg/summary/collector_test.go
  pkg/summary/summary.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  tests/br_full_ddl/run.sh
  tests/br_full_index/run.sh
  tests/run.sh
Labels: enhancement

#209 task: do not run checksum if restore failed
  pkg/task/restore.go
  pkg/task/restore_raw.go
Labels: LGT1

#199 fix incremental bug in llroad test
  pkg/backup/client.go
  pkg/backup/schema_test.go
  pkg/restore/db.go
  pkg/task/backup.go
  pkg/task/restore.go
  tests/br_incremental_only_ddl/run.sh
  tests/br_incremental_same_table/run.sh
Labels: bug

#218 Revert "tests: disable TLS test"
  tests/run.sh
Labels: LGT1, enhancement
