Repository pingcap/br, pull requests merged in 2021-08, with the labels that each got.

#1397 lightning: Return error for empty path
  .gitignore
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
Labels: size/M, status/LGT2, status/can-merge

#1144 Detect duplicate data from TiKV
  errors.toml
  pkg/errors/errors.go
  pkg/lightning/backend/backend.go
  pkg/lightning/backend/importer/importer.go
  pkg/lightning/backend/kv/kv2sql.go
  pkg/lightning/backend/kv/sql2kv_test.go
  pkg/lightning/backend/local/duplicate.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/noop/noop.go
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/common/conn.go
  pkg/lightning/config/config.go
  pkg/lightning/restore/checksum.go
  pkg/lightning/restore/restore_test.go
  pkg/lightning/restore/table_restore.go
  pkg/mock/backend.go
  tests/lightning_duplicate_detection/config.toml
  tests/lightning_duplicate_detection/config1.toml
  tests/lightning_duplicate_detection/config2.toml
  tests/lightning_duplicate_detection/run.sh
Labels: component/import, size/XXL, status/LGT2, status/can-merge

#1408 Fix speed compute
  pkg/summary/collector.go
Labels: contribution, first-time-contributor, size/XS, status/LGT2, status/can-merge

#1380 restore: add rater for creating tables
  pkg/logutil/logging_test.go
  pkg/logutil/rate.go
  pkg/restore/client.go
Labels: component/restore, size/L, status/LGT2, status/can-merge

#1402 restore: retry scatter error
  pkg/restore/split.go
  pkg/restore/split_client.go
  pkg/restore/split_test.go
Labels: component/restore, size/L, status/LGT2, status/can-merge

#1387 lightning: auto configure for parallel import
  cmd/br/debug.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/config/config.go
  pkg/lightning/config/config_test.go
  pkg/lightning/config/const.go
  pkg/lightning/lightning_test.go
  pkg/lightning/mydump/csv_parser.go
  pkg/lightning/mydump/csv_parser_test.go
  pkg/lightning/mydump/loader.go
  pkg/lightning/mydump/loader_test.go
  pkg/lightning/mydump/parquet_parser.go
  pkg/lightning/mydump/parser.go
  pkg/lightning/mydump/parser_test.go
  pkg/lightning/mydump/region.go
  pkg/lightning/restore/check_info.go
  pkg/lightning/restore/meta_manager.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
  pkg/lightning/restore/table_restore.go
  pkg/pdutil/pd.go
  pkg/pdutil/pd_test.go
Labels: size/XXL, status/LGT2, status/can-merge

#1364 lightning: make create table ddl compatible with clustered index
  go.mod1
  go.sum1
  pkg/lightning/restore/tidb.go
  pkg/lightning/restore/tidb_test.go
Labels: status/LGT2, status/can-merge, component/import, type/bug-fix, size/M

#1335 backup: refine backup log for tracing backup tasks
  pkg/backup/client.go
  pkg/backup/push.go
  pkg/logutil/context.go
  pkg/logutil/logging_test.go
Labels: status/LGT2, status/can-merge, component/backup, size/L

#1413 lightning: fix the bug that calculate unfinished ranges may miss some range
  pkg/lightning/backend/local/local.go
Labels: status/LGT2, status/can-merge, component/import, type/bug-fix, size/M, needs-cherry-pick-release-5.1

#1336 lightning: check and restore pd scheduler even if our task failed
  pkg/lightning/restore/meta_manager.go
  pkg/lightning/restore/restore.go
Labels: status/LGT2, status/can-merge, component/import, type/bug-fix, size/L, type/cherry-pick-for-release-5.1

#1407 lightning: evaluate all generated columns even if they are virtual
  pkg/lightning/backend/kv/sql2kv.go
  tests/lightning_generated_columns/data/gencol.expr_index-schema.sql
  tests/lightning_generated_columns/data/gencol.expr_index.0.sql
  tests/lightning_generated_columns/data/gencol.nested-schema.sql
  tests/lightning_generated_columns/data/gencol.virtual_only-schema.sql
  tests/lightning_generated_columns/data/gencol.virtual_only.0.sql
  tests/lightning_generated_columns/run.sh
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, status/ptal, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1

#1421 readme: move this repo to tidb
  README.md
Labels: status/LGT2, status/can-merge, size/L

#1414 lightning: better estimate of the max-open-files
  pkg/lightning/backend/local/local_unix.go
  pkg/lightning/lightning.go
  pkg/lightning/lightning_test.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, component/import, status/ptal, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1
