Repository pingcap/br, pull requests merged in 2021-12, with the labels that each got.

#1449 br: Remove statement from closure to prevent concurrent operation during backup system table
  pkg/backup/schema.go
  pkg/backup/schema_test.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-5.0, size/M, do-not-merge/cherry-pick-not-approved

#1441 [cherry-pick] backup: more detailed TiKV error message(tidb#27567)
  pkg/backup/push.go
Labels: status/LGT2, status/can-merge, size/XS, cherry-pick-approved, type/cherry-pick-for-release-5.0

#1454 br: Cherry pick 29601 from tidb repo
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/restore/ingester.go
Labels: status/LGT2, size/XS, do-not-merge/cherry-pick-not-approved

#1438 [cherry-pick] restore: fix failed to retry grpc errors(tidb#27423)
  pkg/restore/import.go
  pkg/utils/backoff.go
  tests/br_full/run.sh
Labels: status/LGT2, status/can-merge, size/S, cherry-pick-approved, type/cherry-pick-for-release-5.0
