Repository pingcap/br, pull requests merged in 2021-06, with the labels that each got.

#1156 storage: mkdirAll for local storage even when SkipCheckPath is true
  pkg/storage/storage.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, status/LGT2, status/can-merge

#1160 tests/br: fix bug in issue #1158
  tests/_utils/run_services
Labels: size/XS, status/LGT2, status/can-merge

#1161 tests/br/compatibility: fix failed for manifest unknown
  compatibility/get_last_tags.sh
  compatibility/prepare_backup.sh
  tests/run_compatible.sh
Labels: size/M, status/LGT2, status/can-merge

#1159 *: upgrade go version from 1.13/1.15 to 1.16
  .github/workflows/build.yml
  .github/workflows/compatible_test.yml
  CONTRIBUTING.md
  README.md
  docker/Dockerfile
  go.mod1
  go.sum1
  pkg/storage/gcs.go
  tests/up.sh
  tools/go.mod
  web/go.mod
Labels: component/test, size/M, status/LGT2, status/can-merge

#1170 action trigger: fix compatibility trigger bug on push
  .github/workflows/build.yml
  .github/workflows/compatible_test.yml
  tests/_utils/run_services
Labels: component/test, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, status/LGT2, status/can-merge

#1153 go.mod: update tidb to the new version
  cmd/br/cmd.go
  go.mod1
  go.sum1
  pkg/backup/client.go
  pkg/conn/conn.go
  pkg/lightning/backend/kv/session.go
  tests/br_key_locked/locker.go
Labels: size/L, status/LGT2, status/can-merge

#784 lightning: support restore data into tables that contains data
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/checkpoints/checkpoints.go
  pkg/lightning/checkpoints/checkpoints_file_test.go
  pkg/lightning/checkpoints/checkpoints_sql_test.go
  pkg/lightning/checkpoints/checkpointspb/file_checkpoints.pb.go
  pkg/lightning/checkpoints/checkpointspb/file_checkpoints.proto
  pkg/lightning/common/util.go
  pkg/lightning/config/config.go
  pkg/lightning/restore/meta_manager.go
  pkg/lightning/restore/meta_manager_test.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
  pkg/pdutil/pd.go
  tests/lightning_checkpoint/run.sh
  tests/lightning_checkpoint_chunks/run.sh
  tests/lightning_error_summary/data/error_summary.c.sql
  tests/lightning_incremental/config.toml
  tests/lightning_incremental/data/incr-schema-create.sql
  tests/lightning_incremental/data/incr.auto_random-schema.sql
  tests/lightning_incremental/data/incr.auto_random.sql
  tests/lightning_incremental/data/incr.pk_auto_inc-schema.sql
  tests/lightning_incremental/data/incr.pk_auto_inc.sql
  tests/lightning_incremental/data/incr.rowid_uk_inc-schema.sql
  tests/lightning_incremental/data/incr.rowid_uk_inc.sql
  tests/lightning_incremental/data/incr.uk_auto_inc-schema.sql
  tests/lightning_incremental/data/incr.uk_auto_inc.sql
  tests/lightning_incremental/data1/incr-schema-create.sql
  tests/lightning_incremental/data1/incr.auto_random-schema.sql
  tests/lightning_incremental/data1/incr.auto_random.sql
  tests/lightning_incremental/data1/incr.pk_auto_inc-schema.sql
  tests/lightning_incremental/data1/incr.pk_auto_inc.sql
  tests/lightning_incremental/data1/incr.rowid_uk_inc-schema.sql
  tests/lightning_incremental/data1/incr.rowid_uk_inc.sql
  tests/lightning_incremental/data1/incr.uk_auto_inc-schema.sql
  tests/lightning_incremental/data1/incr.uk_auto_inc.sql
  tests/lightning_incremental/run.sh
  tests/lightning_local_backend/run.sh
  tests/lightning_tidb_rowid/run.sh
  tidb-lightning.toml
Labels: component/import, size/XXL, status/LGT2, status/can-merge, status/ptal

#1080 lightning: save chunk checkpoint timely
  pkg/lightning/backend/backend.go
  pkg/lightning/backend/backend_test.go
  pkg/lightning/backend/importer/importer.go
  pkg/lightning/backend/importer/importer_test.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/local_test.go
  pkg/lightning/backend/noop/noop.go
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/backend/tidb/tidb_test.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
  pkg/mock/backend.go
Labels: component/import, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XL, status/LGT2, status/can-merge, status/ptal

#1164 lightning: do not retry sql.ErrNoRows error
  pkg/lightning/checkpoints/checkpoints_sql_test.go
  pkg/lightning/common/util.go
Labels: component/import, size/M, status/LGT2, status/can-merge, status/ptal

#1178 lightning: fix id allocator base for double auto_increment field
  pkg/kv/kv.go
  pkg/lightning/backend/kv/sql2kv.go
  pkg/lightning/backend/kv/sql2kv_test.go
Labels: component/import, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, type/bug-fix

#1134 lightning: fix split larget csv EOF error
  pkg/lightning/mydump/region.go
  pkg/lightning/mydump/region_test.go
Labels: component/import, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, status/LGT2, status/can-merge, type/bug-fix

#1184 lightning: avoid do pre-checksum when checksum is disabled
  pkg/lightning/restore/meta_manager.go
  pkg/lightning/restore/meta_manager_test.go
  pkg/lightning/restore/restore.go
Labels: component/import, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#999 Lightning: add a pre check before import starts.
  errors.toml
  go.mod1
  go.sum1
  pkg/errors/errors.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/common/storage_unix.go
  pkg/lightning/common/storage_windows.go
  pkg/lightning/config/config.go
  pkg/lightning/config/global.go
  pkg/lightning/lightning.go
  pkg/lightning/mydump/loader.go
  pkg/lightning/mydump/loader_test.go
  pkg/lightning/restore/check_info.go
  pkg/lightning/restore/check_template.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
  pkg/storage/gcs.go
  pkg/storage/gcs_test.go
  pkg/storage/local.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
  pkg/task/common.go
  tests/lightning_concurrent-restore/run.sh
  tests/lightning_default-columns/run.sh
  tests/lightning_no_schema/run.sh
  tests/lightning_no_schema/schema-data/noschema-schema-create.sql
  tests/lightning_no_schema/schema-data/noschema.t-schema.sql
  tests/lightning_tidb_duplicate_data/run.sh
  tests/lightning_unused_config_keys/run.sh
Labels: component/import, needs-cherry-pick-release-5.1, size/XXL, status/LGT2, status/can-merge

#1171 backup: optimize backupmeta to reduce memory useage.
  cmd/br/debug.go
  errors.toml
  go.mod1
  go.sum1
  pkg/backup/client.go
  pkg/backup/client_test.go
  pkg/backup/schema.go
  pkg/backup/schema_test.go
  pkg/checksum/executor.go
  pkg/checksum/executor_test.go
  pkg/checksum/validate.go
  pkg/errors/errors.go
  pkg/lightning/mydump/reader_test.go
  pkg/metautil/metafile.go
  pkg/metautil/metafile_test.go
  pkg/mock/storage/storage.go
  pkg/restore/batcher_test.go
  pkg/restore/client.go
  pkg/restore/client_test.go
  pkg/restore/db.go
  pkg/restore/db_test.go
  pkg/restore/pipeline_items.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/utils/schema.go
  pkg/utils/schema_test.go
  tests/br_backup_version/run.sh
  tests/br_s3/run.sh
Labels: component/backup, component/restore, component/util, needs-cherry-pick-release-5.1, release-blocker, size/XXL, status/LGT2, status/can-merge

#1020 lightning: optimize lightning memory and perf
  pkg/lightning/backend/kv/session.go
  pkg/lightning/backend/kv/sql2kv.go
  pkg/lightning/backend/kv/sql2kv_test.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
  pkg/restore/merge.go
Labels: component/import, needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge, status/ptal, type/performance

#757 lightning/backend: support shard row id for local/importer backend
  pkg/lightning/backend/kv/sql2kv.go
  pkg/lightning/backend/kv/sql2kv_test.go
  tests/lightning_shard_rowid/config.toml
  tests/lightning_shard_rowid/data/shard_rowid-schema-create.sql
  tests/lightning_shard_rowid/data/shard_rowid.shr-schema.sql
  tests/lightning_shard_rowid/data/shard_rowid.shr.0.sql
  tests/lightning_shard_rowid/run.sh
Labels: component/import, needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge

#1198 mod: update pd dependence to make ci passed.
  go.mod1
  go.sum1
  pkg/lightning/backend/local/localhelper_test.go
  pkg/pdutil/pd_test.go
  pkg/restore/split_test.go
Labels: needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#1194 lightning: more flexiable region max keys
  pkg/lightning/backend/kv/sql2kv_test.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/localhelper.go
  pkg/logutil/logging.go
  tests/lightning_checkpoint_engines_order/run.sh
Labels: component/import, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#1205 *: use tikv/client-go/v2
  go.mod1
  go.sum1
  pkg/backup/client.go
  pkg/backup/client_test.go
  pkg/conn/conn.go
  pkg/lightning/backend/backend_test.go
  pkg/lightning/restore/checksum.go
  pkg/lightning/restore/checksum_test.go
  pkg/lightning/restore/restore.go
  pkg/mock/mock_cluster.go
  pkg/restore/client.go
  pkg/restore/db_test.go
  pkg/restore/log_client.go
  pkg/task/backup.go
  tests/br_backup_empty/run.sh
  tests/br_backup_version/run.sh
  tests/br_key_locked/locker.go
  tests/br_rawkv/client.go
  tests/br_z_gc_safepoint/gc.go
  tests/docker_compatible_gcs/prepare.sh
  tests/docker_compatible_gcs/run.sh
  tests/docker_compatible_s3/prepare.sh
  tests/docker_compatible_s3/run.sh
Labels: size/M, status/LGT2, status/can-merge

#1204 mod: update tidb pkg version
  go.mod1
  go.sum1
Labels: cherry-pick-approved, size/XS, status/LGT2, status/can-merge

#1207 restore: Fix system tables are filtered bug
  pkg/task/restore.go
  pkg/utils/schema.go
  tests/br_systables/run.sh
Labels: component/restore, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#1210 *: update tidb and enable integration tests
  go.mod1
  go.sum1
  tests/br_backup_empty/run.sh
  tests/br_backup_version/run.sh
  tests/docker_compatible_gcs/prepare.sh
  tests/docker_compatible_gcs/run.sh
  tests/docker_compatible_s3/prepare.sh
  tests/docker_compatible_s3/run.sh
Labels: size/M, status/LGT2, status/can-merge

#1220 Lightning: skip print check template and remove unnecessary check
  pkg/lightning/mydump/loader.go
  pkg/lightning/mydump/loader_test.go
  pkg/lightning/restore/restore.go
Labels: component/import, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#1223 backup: fix ddl unmarshal error in meta v2
  pkg/metautil/metafile.go
  pkg/restore/db_test.go
Labels: component/backup, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#1212 tests: fix shell stuck while br is exited with failure status
  tests/br_tikv_outage/run.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#1172 test: Add a test case that covers --send-credentials-to-tikv flag
  pkg/backup/client_test.go
Labels: component/test, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#1241 test: reduce the time spent on test disk quota
  tests/lightning_disk_quota/config.toml
  tests/lightning_disk_quota/run.sh
Labels: component/import, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#1243 restore: fix [files lost] in log info
  pkg/restore/client.go
  tests/lightning_checkpoint_engines_order/run.sh
Labels: component/restore, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#1247 check: increase threshold to avoid false positive read flow check
  pkg/lightning/restore/check_info.go
  pkg/lightning/restore/restore_test.go
Labels: component/import, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#1176 log: Improve Error: backup lock exists
  pkg/backup/client.go
  pkg/summary/collector.go
Labels: component/backup, size/S, status/LGT2, status/can-merge

#1248 storage: fix noop writer to help dumpling to do some tests
  pkg/storage/noop.go
Labels: size/S, status/LGT2, status/can-merge

#1101 lightning: make every engine use a unique commitTS
  pkg/lightning/backend/backend.go
  pkg/lightning/backend/backend_test.go
  pkg/lightning/backend/importer/importer.go
  pkg/lightning/backend/importer/importer_test.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/local_test.go
  pkg/lightning/backend/noop/noop.go
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/backend/tidb/tidb_test.go
  pkg/lightning/lightning.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
  pkg/mock/backend.go
Labels: component/import, size/XL, status/LGT2, status/can-merge

#1259 systable: add more sys tables to blocklist
  pkg/restore/systable_restore.go
  tests/br_systables/run.sh
Labels: component/restore, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#1261 lightning: fix panic in `nextKey`
  pkg/lightning/backend/local/local.go
Labels: size/XS, status/LGT2, status/can-merge

#1235 pkg/conn/conn_test: remove github.com/tikv/pd/server/core
  pkg/conn/conn_test.go
Labels: size/XS, status/LGT2, status/can-merge

#1272 lightning: fix parquet parser for decimal type
  pkg/lightning/mydump/examples/test.parquet
  pkg/lightning/mydump/parquet_parser.go
  pkg/lightning/mydump/parquet_parser_test.go
Labels: component/import, size/XL, status/LGT2, status/can-merge, type/bug-fix, type/cherry-pick-for-release-4.0, type/cherry-pick-for-release-5.0, type/cherry-pick-for-release-5.1

#1234 cmd/br/debug.go: use br/pkg/mock/mockid instead of pd/pkg/mock/mockid
  cmd/br/debug.go
  pkg/mock/mockid/mockid.go
Labels: size/M, status/LGT2, status/can-merge

#1240 lightning: use region info to split region
  cmd/tidb-lightning-ctl/main.go
  pkg/lightning/backend/backend.go
  pkg/lightning/backend/backend_test.go
  pkg/lightning/backend/importer/importer.go
  pkg/lightning/backend/importer/importer_test.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/localhelper.go
  pkg/lightning/backend/local/localhelper_test.go
  pkg/lightning/backend/noop/noop.go
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
  pkg/mock/backend.go
Labels: component/import, size/L, status/LGT2, status/can-merge, status/ptal

#1256 tests: fix br_tikv_outage learner bug
  tests/br_tikv_outage/run.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#1280 Fixed check-requirements error message
  pkg/lightning/restore/restore.go
Labels: component/import, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#1279 restore: remove table field from rewrite rules
  cmd/br/debug.go
  pkg/restore/batcher_test.go
  pkg/restore/client.go
  pkg/restore/client_test.go
  pkg/restore/range.go
  pkg/restore/range_test.go
  pkg/restore/split.go
  pkg/restore/split_test.go
  pkg/restore/util.go
  pkg/restore/util_test.go
Labels: component/restore, size/M, status/LGT2, status/can-merge

#1287 lightning: fix disk quota check message
  pkg/lightning/restore/check_info.go
Labels: size/XS, status/LGT2, status/can-merge

#1271 lightning: make `tikv-importer.backend` required
  pkg/lightning/checkpoints/checkpoints_file_test.go
  pkg/lightning/checkpoints/checkpoints_sql_test.go
  pkg/lightning/config/config.go
  pkg/lightning/config/config_test.go
  pkg/lightning/config/global.go
  pkg/lightning/lightning_test.go
  pkg/lightning/restore/restore_test.go
  tests/lightning_black-white-list/config.toml
  tests/lightning_black-white-list/even-table-only.toml
  tests/lightning_black-white-list/firstdb-only.toml
  tests/lightning_character_sets/auto.toml
  tests/lightning_character_sets/binary.toml
  tests/lightning_character_sets/gb18030.toml
  tests/lightning_character_sets/utf8mb4.toml
  tests/lightning_checkpoint_chunks/config.toml
  tests/lightning_checkpoint_chunks/file.toml
  tests/lightning_checkpoint_dirty_tableid/file.toml
  tests/lightning_checkpoint_dirty_tableid/mysql.toml
  tests/lightning_checkpoint_error_destroy/file.toml
  tests/lightning_checkpoint_error_destroy/mysql.toml
  tests/lightning_checkpoint_timestamp/config.toml
  tests/lightning_checkpoint_timestamp/mysql.toml
  tests/lightning_cmdline_override/run.sh
  tests/lightning_concurrent-restore/config.toml
  tests/lightning_default-columns/config.toml
  tests/lightning_error_summary/config.toml
  tests/lightning_examples/1.toml
  tests/lightning_examples/131072.toml
  tests/lightning_examples/512.toml
  tests/lightning_exotic_filenames/config.toml
  tests/lightning_no_schema/config.toml
  tests/lightning_restore/config.toml
  tests/lightning_routes/config.toml
  tests/lightning_row-format-v2/config.toml
  tests/lightning_sqlmode/off.toml
  tests/lightning_sqlmode/on.toml
  tests/lightning_tool_135/config.toml
  tests/lightning_tool_1420/config.toml
  tests/lightning_tool_1472/config.toml
  tests/lightning_tool_241/config.toml
Labels: size/L, status/LGT2, status/can-merge

#1236 go.mod: update tidb to new version
  go.mod1
  go.sum1
  pkg/lightning/mydump/router.go
Labels: size/S, status/LGT2, status/can-merge

#1293 lightning: fix parquet parser for decimal type (#1272) (#1277)
  pkg/lightning/mydump/examples/test.parquet
  pkg/lightning/mydump/parquet_parser.go
  pkg/lightning/mydump/parquet_parser_test.go
Labels: component/import, do-not-merge/cherry-pick-not-approved, size/XL, type/bug-fix

#1298 compatibility: filter the tags don't have corresponding docker images
  compatibility/get_last_tags.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, status/LGT2, status/can-merge, type/compatibility

#1126 lightning: implement engine local duplicate detection
  errors.toml
  pkg/errors/errors.go
  pkg/lightning/backend/backend.go
  pkg/lightning/backend/kv/sql2kv.go
  pkg/lightning/backend/kv/sql2kv_test.go
  pkg/lightning/backend/kv/types.go
  pkg/lightning/backend/local/iterator.go
  pkg/lightning/backend/local/iterator_test.go
  pkg/lightning/backend/local/key_adapter.go
  pkg/lightning/backend/local/key_adapter_test.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/local_test.go
  pkg/lightning/backend/local/localhelper.go
  pkg/lightning/backend/noop/noop.go
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/backend/tidb/tidb_test.go
  pkg/lightning/common/util.go
  pkg/lightning/config/config.go
  pkg/lightning/restore/restore.go
  pkg/mock/kv.go
  tests/lightning_duplicate_detection/config.toml
  tests/lightning_duplicate_detection/data/dup_detect-schema-create.sql
  tests/lightning_duplicate_detection/data/dup_detect.ta-schema.sql
  tests/lightning_duplicate_detection/data/dup_detect.ta.0.sql
  tests/lightning_duplicate_detection/data/dup_detect.ta.1.sql
  tests/lightning_duplicate_detection/data/dup_detect.tb-schema.sql
  tests/lightning_duplicate_detection/data/dup_detect.tb.0.sql
  tests/lightning_duplicate_detection/data/dup_detect.tb.1.sql
  tests/lightning_duplicate_detection/data/dup_detect.tc-schema.sql
  tests/lightning_duplicate_detection/data/dup_detect.tc.0.sql
  tests/lightning_duplicate_detection/data/dup_detect.tc.1.sql
  tests/lightning_duplicate_detection/data/dup_detect.td-schema.sql
  tests/lightning_duplicate_detection/data/dup_detect.td.0.sql
  tests/lightning_duplicate_detection/data/dup_detect.td.1.sql
  tests/lightning_duplicate_detection/data/dup_detect.te-schema.sql
  tests/lightning_duplicate_detection/data/dup_detect.te.0.sql
  tests/lightning_duplicate_detection/data/dup_detect.te.1.sql
  tests/lightning_duplicate_detection/data/dup_detect.tf-schema.sql
  tests/lightning_duplicate_detection/data/dup_detect.tf.0.sql
  tests/lightning_duplicate_detection/data/dup_detect.tf.1.sql
  tests/lightning_duplicate_detection/run.sh
Labels: size/XXL, status/LGT2, status/can-merge
