Repository pingcap/br, pull requests merged in 2021-04, with the labels that each got.

#976 go.mod: update TiDB
  go.mod1
  go.sum1
Labels: cherry-pick-approved, size/XS, status/LGT2, status/can-merge

#979 makefile: fix the issue that build the wrong version when not in release branch
  Makefile
Labels: cherry-pick-approved, severity/minor, size/XS, status/LGT2, status/can-merge, type/5.0-cherry-pick

#978 makefile: fix wrong release version build
  Makefile
Labels: needs-cherry-pick-4.0, severity/minor, status/LGT2, status/can-merge

#967 check table is empty before do import
  pkg/lightning/restore/restore.go
Labels: size/M, status/LGT2, status/can-merge

#766 lightning: Fix lints for lightning
  Makefile
  cmd/tidb-lightning-ctl/main.go
  cmd/tidb-lightning-ctl/main_test.go
  cmd/tidb-lightning/main.go
  cmd/tidb-lightning/main_test.go
  pkg/lightning/backend/backend_test.go
  pkg/lightning/backend/importer/importer.go
  pkg/lightning/backend/kv/session.go
  pkg/lightning/backend/kv/sql2kv.go
  pkg/lightning/backend/kv/sql2kv_test.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/local_test.go
  pkg/lightning/backend/local/localhelper_test.go
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/backend/tidb/tidb_test.go
  pkg/lightning/checkpoints/checkpoints.go
  pkg/lightning/checkpoints/checkpoints_file_test.go
  pkg/lightning/checkpoints/glue_checkpoint.go
  pkg/lightning/common/pause_test.go
  pkg/lightning/common/security_test.go
  pkg/lightning/common/util.go
  pkg/lightning/common/util_test.go
  pkg/lightning/config/config.go
  pkg/lightning/config/configlist.go
  pkg/lightning/glue/glue.go
  pkg/lightning/lightning.go
  pkg/lightning/lightning_test.go
  pkg/lightning/log/log.go
  pkg/lightning/metric/metric.go
  pkg/lightning/mydump/csv_parser.go
  pkg/lightning/mydump/loader.go
  pkg/lightning/mydump/loader_test.go
  pkg/lightning/mydump/parser.go
  pkg/lightning/mydump/reader_test.go
  pkg/lightning/mydump/region.go
  pkg/lightning/mydump/region_test.go
  pkg/lightning/mydump/router.go
  pkg/lightning/mydump/router_test.go
  pkg/lightning/restore/checksum.go
  pkg/lightning/restore/checksum_test.go
  pkg/lightning/restore/const.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
  pkg/lightning/restore/tidb.go
  pkg/lightning/restore/tidb_test.go
  pkg/lightning/tikv/tikv_test.go
  pkg/lightning/web/progress.go
  pkg/mock/glue.go
Labels: component/import, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XXL, status/LGT2, status/can-merge, status/ptal

#990 *: remove useless fetch
  pkg/checksum/executor.go
Labels: first-time-contributor, size/XS, status/LGT2, status/can-merge

#985 Fix check empty table in checkpoint enabled case
  pkg/lightning/checkpoints/checkpoints.go
  pkg/lightning/checkpoints/checkpoints_file_test.go
  pkg/lightning/checkpoints/checkpoints_sql_test.go
  pkg/lightning/restore/restore.go
  tests/lightning_error_summary/run.sh
  tests/lightning_local_backend/run.sh
Labels: component/import, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/L, status/LGT2, status/can-merge

#998 lightning: Fix lints for lightning (#766)
  Makefile
  cmd/tidb-lightning-ctl/main.go
  cmd/tidb-lightning-ctl/main_test.go
  cmd/tidb-lightning/main.go
  cmd/tidb-lightning/main_test.go
  pkg/lightning/backend/backend_test.go
  pkg/lightning/backend/importer/importer.go
  pkg/lightning/backend/kv/session.go
  pkg/lightning/backend/kv/sql2kv.go
  pkg/lightning/backend/kv/sql2kv_test.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/local_test.go
  pkg/lightning/backend/local/localhelper_test.go
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/backend/tidb/tidb_test.go
  pkg/lightning/checkpoints/checkpoints.go
  pkg/lightning/checkpoints/checkpoints_file_test.go
  pkg/lightning/checkpoints/glue_checkpoint.go
  pkg/lightning/common/pause_test.go
  pkg/lightning/common/security_test.go
  pkg/lightning/common/util.go
  pkg/lightning/common/util_test.go
  pkg/lightning/config/config.go
  pkg/lightning/config/configlist.go
  pkg/lightning/glue/glue.go
  pkg/lightning/lightning.go
  pkg/lightning/lightning_test.go
  pkg/lightning/log/log.go
  pkg/lightning/metric/metric.go
  pkg/lightning/mydump/csv_parser.go
  pkg/lightning/mydump/loader.go
  pkg/lightning/mydump/loader_test.go
  pkg/lightning/mydump/parser.go
  pkg/lightning/mydump/reader_test.go
  pkg/lightning/mydump/region.go
  pkg/lightning/mydump/region_test.go
  pkg/lightning/mydump/router.go
  pkg/lightning/mydump/router_test.go
  pkg/lightning/restore/checksum.go
  pkg/lightning/restore/checksum_test.go
  pkg/lightning/restore/const.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
  pkg/lightning/restore/tidb.go
  pkg/lightning/restore/tidb_test.go
  pkg/lightning/tikv/tikv_test.go
  pkg/lightning/web/progress.go
  pkg/mock/glue.go
Labels: cherry-pick-approved, component/import, size/XXL, status/LGT2, status/can-merge, status/ptal, type/5.0-cherry-pick

#991 makefile: fix build the wrong version when branch in refs/tags/*
  Makefile
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, severity/minor, size/XS, status/LGT2, status/can-merge

#996 pkg/lightning: fix incorrect table counter
  pkg/lightning/restore/restore_test.go
  pkg/lightning/restore/tidb.go
  pkg/lightning/restore/tidb_test.go
Labels: component/import, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/M, status/LGT2, status/can-merge, type/bug-fix

#981 debug: make the marshalled JSON from backup meta more human readable.
  cmd/br/debug.go
  pkg/utils/json.go
  pkg/utils/json_test.go
Labels: component/util, size/XL, status/LGT2, status/can-merge

#970 collector: remove cputime
  pkg/restore/client.go
  pkg/summary/collector.go
  pkg/summary/collector_test.go
  tests/br_split_region_fail/run.sh
Labels: component/backup, component/restore, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/M, status/LGT2, status/can-merge

#1006 test: fix unstable integration test lightning_checkpoint
  pkg/lightning/lightning_test.go
  tests/lightning_checkpoint/run.sh
Labels: component/import, component/test, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XS, status/LGT2, status/can-merge

#708 Compatibility test: create github actions for test
  .github/workflows/compatible_test.yml
  COMPATIBILITY_TEST.md
  Makefile
  README.md
  compatibility/backup_cluster.yaml
  compatibility/credentials/application_default_credentials.json
  compatibility/prepare_backup.sh
  compatibility/prepare_data/workload
  docker-compose.yaml
  docker/gcs.env
  tests/_utils/run_sql_in_container
  tests/docker_compatible_gcs/prepare.sh
  tests/docker_compatible_gcs/run.sh
  tests/docker_compatible_s3/prepare.sh
  tests/docker_compatible_s3/run.sh
  tests/run_compatible.sh
Labels: component/test, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XXL, status/LGT2, status/can-merge, status/need-compatible-tests, status/ptal, type/compatibility

#1014 test: fix the unstable unit test
  pkg/lightning/lightning_test.go
Labels: component/test, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XS, status/LGT2, status/can-merge

#997 backup: allow backup tolerate minor TiKV failure
  Makefile
  errors.toml
  pkg/backup/client.go
  pkg/backup/push.go
  pkg/conn/conn.go
  pkg/errors/errors.go
  tests/_utils/run_services
  tests/br_serv_outage/run.sh
  tests/br_serv_outage/workload
Labels: component/backup, needs-cherry-pick-5.0, size/XL, status/LGT2, status/can-merge

#1003 log: delete lightning's redact package
  pkg/lightning/backend/kv/sql2kv.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/localhelper.go
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/lightning.go
  pkg/lightning/log/redact.go
  pkg/logutil/logging.go
Labels: size/L, status/LGT2, status/can-merge

#1021 test: remove the right importer data
  tests/lightning_checkpoint_engines/run.sh
Labels: component/import, component/test, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XS, status/LGT2, status/can-merge

#1015 backup: set concurrency to 1 when ratelimit enabled
  pkg/logutil/logging.go
  pkg/task/backup.go
  pkg/task/common.go
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/M, status/LGT2, status/can-merge

#1022 tests: remove br_serv_outage ratelimit
  tests/br_tikv_outage/run.sh
  tests/br_tikv_outage/workload
Labels: component/test, needs-cherry-pick-5.0, size/XS, status/LGT2, status/can-merge

#1028 *: update TiDB
  go.mod1
  go.sum1
Labels: cherry-pick-approved, size/S, status/LGT2, status/can-merge

#1030 test: fix unstable test lightning_fail_fast
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/lightning_test.go
  pkg/lightning/restore/restore.go
  tests/lightning_fail_fast/run.sh
Labels: component/import, component/test, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/S, status/LGT2, status/can-merge

#1035 *: update tidb
  go.mod1
  go.sum1
  pkg/backup/client_test.go
Labels: size/M, status/LGT2, status/can-merge

#1036 backup: debounce fine-grained backup
  pkg/backup/client.go
Labels: component/backup, needs-cherry-pick-5.0, size/S, status/LGT2, status/can-merge

#905 pkg/lightning: let batch split keys also consider the raft entry limit
  pkg/lightning/backend/local/localhelper.go
  pkg/lightning/backend/local/localhelper_test.go
Labels: component/import, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/L, status/LGT2, status/can-merge, type/bug-fix

#1033 summary: log failure message to terminal
  pkg/summary/collector.go
Labels: component/util, needs-cherry-pick-5.0, size/XS, status/LGT2, status/can-merge

#986 pkg/lightning: only retry unfinished ranges when retry import engine
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/local_test.go
Labels: component/import, size/XL, status/LGT2, status/can-merge, status/ptal, type/enhancement

#1047 backup: optimize progress update logic
  .github/workflows/compatible_test.yml
  pkg/backup/client.go
  pkg/backup/push.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  tests/br_300_small_tables/run.sh
  tests/br_db/run.sh
Labels: component/backup, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/L, status/LGT2, status/can-merge

#1038 doc: add tiup Quick Start in README.md
  README.md
Labels: contribution, first-time-contributor, size/M, status/LGT2, status/can-merge

#1052 Makefile: fix version number on macOS
  Makefile
Labels: cherry-pick-approved, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/S, status/LGT2, status/can-merge

#1051 action: add multiple os build check
  .github/workflows/build.yml
  pkg/utils/dyn_pprof_other.go
Labels: component/test, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/M, status/LGT2, status/can-merge

#1049 lightning: fix wrong error message of restoring table
  pkg/lightning/mydump/loader.go
  pkg/lightning/mydump/loader_test.go
  pkg/lightning/restore/restore.go
Labels: component/import, contribution, first-time-contributor, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/M, status/LGT2, status/can-merge

#753 linghtning/backend: optimize local writer concurrency and memory usage
  pkg/lightning/backend/backend.go
  pkg/lightning/backend/backend_test.go
  pkg/lightning/backend/importer/importer.go
  pkg/lightning/backend/importer/importer_test.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/local_test.go
  pkg/lightning/backend/noop/noop.go
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/backend/tidb/tidb_test.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
  pkg/mock/backend.go
  pkg/utils/math.go
  pkg/utils/math_test.go
  tests/lightning_checkpoint_engines_order/run.sh
  tests/lightning_disk_quota/run.sh
Labels: component/import, needs-cherry-pick-4.0, needs-cherry-pick-5.0, require-LGT3, size/XXL, status/LGT3, status/can-merge, type/enhancement

#1048 backup,restore: support backing up / restore system databases
  cmd/br/backup.go
  cmd/br/cmd.go
  cmd/br/restore.go
  errors.toml
  pkg/backup/client.go
  pkg/backup/schema.go
  pkg/backup/schema_test.go
  pkg/errors/errors.go
  pkg/gluetidb/glue.go
  pkg/restore/systable_restore.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/utils/schema.go
  tests/br_full_ddl/run.sh
  tests/br_full_index/run.sh
  tests/br_systables/run.sh
  tests/br_systables/workload
Labels: component/backup, component/restore, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XL, status/LGT2, status/can-merge
