Repository pingcap/br, pull requests merged in 2021-09, with the labels that each got.

#1431 web: mute the alert
  pkg/lightning/web/res_vfsdata.go
  web/package-lock.json
Labels: status/LGT2, status/can-merge, size/XXL

#1432 [cherry-pick] br: less split during restoring(tidb#27240)
  pkg/restore/import.go
  pkg/restore/split.go
  pkg/restore/split_test.go
  pkg/restore/util.go
  pkg/restore/util_test.go
Labels: status/LGT2, status/can-merge, type/4.0-cherry-pick, size/L, cherry-pick-approved

#1428 [cherry-pick] br: add region range check for batch scan regions(tidb#27192)
  errors.toml
  pkg/errors/errors.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/localhelper.go
  pkg/lightning/backend/local/localhelper_test.go
  pkg/restore/split.go
  pkg/restore/util.go
  pkg/restore/util_test.go
Labels: status/LGT2, status/can-merge, type/4.0-cherry-pick, size/L, cherry-pick-approved

#1429 [cherry-pick] restore: split & scatter regions concurrently(tidb#27034)
  pkg/logutil/logging.go
  pkg/restore/import.go
  pkg/restore/pipeline_items.go
  pkg/restore/range.go
  pkg/restore/split.go
  pkg/task/restore.go
  pkg/utils/worker.go
Labels: status/LGT2, status/can-merge, type/4.0-cherry-pick, size/L, cherry-pick-approved

#1424 [cherry-pick] skip rebase auto id(#27199)
  pkg/restore/db.go
  tests/br_views_and_sequences/run.sh
Labels: status/LGT2, status/can-merge, type/4.0-cherry-pick, size/M, cherry-pick-approved

#1433 BR: retry for PD request error and TiKV IO error (#27803)
  pkg/backup/client.go
  pkg/conn/conn.go
  pkg/conn/conn_test.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/utils/backoff.go
  pkg/utils/backoff_test.go
  pkg/utils/retry.go
Labels: status/LGT2, status/can-merge, size/L, cherry-pick-approved

#1334 lightning: avoid directly return error if send check multi ingest request failed
  pkg/lightning/backend/local/local.go
Labels: status/LGT2, status/can-merge, component/import, size/M, needs-cherry-pick-release-5.1
