Repository pingcap/br, pull requests merged in 2021-02, with the labels that each got.

#731 test: fix br incremental index not stable (#468)
  pkg/backup/client.go
  pkg/task/backup.go
  tests/br_incremental_index/run.sh
Labels: component/backup, status/LGT2, type/4.0-cherry-pick, type/bug-fix

#713 storage: fix s3 storage walk-dir with empty sub-dir
  pkg/storage/s3.go
  pkg/storage/s3_test.go
Labels: component/external-storage, needs-cherry-pick-4.0, status/LGT2, type/bug-fix

#728 go.mod: update tidb
  go.mod1
  go.sum1
  tests/br_rawkv/client.go
Labels: component/dependency, status/LGT2, status/can-merge

#738 stats: fix integration test
  tests/br_full_ddl/run.sh
Labels: component/test, status/LGT2, status/can-merge, type/bug-fix

#744 pkg/utils: speed up LoadBackupMeta
  pkg/utils/schema.go
  pkg/utils/schema_test.go
Labels: component/backup, needs-cherry-pick-4.0, status/LGT2, status/can-merge, type/performance

#742 web: update Lightning web interface dependencies
  pkg/lightning/web/res_vfsdata.go
  web/package-lock.json
  web/package.json
Labels: component/import, status/LGT2, status/can-merge

#743 *: update tidb and prepare for upcoming refactor
  errors.toml
  go.mod1
  go.sum1
  pkg/backup/client.go
  pkg/conn/conn.go
  pkg/errors/errors.go
  pkg/gluetikv/glue.go
  pkg/lightning/restore/checksum.go
  pkg/task/backup.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_log.go
  pkg/task/restore_raw.go
  tests/br_key_locked/locker.go
Labels: component/dependency, status/LGT2

#690 tests: add testing Dockerfile
  .gitignore
  go.mod1
  go.sum1
  tests/README.md
  tests/br_full_ddl/run.sh
  tests/up.sh
Labels: component/test, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#737 Add log to make error more clear when restore error using s3 sink
  pkg/storage/s3.go
  pkg/storage/s3_test.go
Labels: first-time-contributor, status/LGT2, status/can-merge

#750 storage: fix s3 walk directory
  pkg/storage/s3.go
  pkg/storage/s3_test.go
Labels: component/external-storage, needs-cherry-pick-4.0, status/LGT2, status/can-merge, type/bug-fix

#759 build: enable cgo by default
  Makefile
  tests/br_table_partition/prepare.sh
  tests/br_table_partition/run.sh
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge

#758 ci: remove circle ci config
  .circleci/config.yml
Labels: component/test, status/LGT2, status/can-merge
