Repository pingcap/br, pull requests merged in 2021-07, with the labels that each got.

#1292 *: remove deprecated io/ioutil
  pkg/lightning/checkpoints/checkpoints.go
  pkg/lightning/common/security.go
  pkg/lightning/common/security_test.go
  pkg/lightning/common/util.go
  pkg/lightning/config/global.go
  pkg/lightning/lightning.go
  pkg/lightning/mydump/loader_test.go
  pkg/lightning/mydump/reader_test.go
  pkg/lightning/mydump/region_test.go
  pkg/lightning/restore/restore_test.go
  pkg/mock/mock_cluster.go
  pkg/pdutil/pd.go
  pkg/restore/split_client.go
  pkg/storage/compress.go
  pkg/storage/compress_test.go
  pkg/storage/gcs.go
  pkg/storage/gcs_test.go
  pkg/storage/local.go
  pkg/storage/parse_test.go
  pkg/storage/s3.go
  pkg/storage/s3_test.go
  pkg/storage/storage.go
  pkg/storage/writer_test.go
  pkg/trace/tracing_test.go
  tests/br_key_locked/locker.go
Labels: size/L, status/LGT2, status/can-merge

#1297 lightning/mydump: support mydumper.csv.terminator
  pkg/lightning/config/config.go
  pkg/lightning/mydump/csv_parser.go
  pkg/lightning/mydump/csv_parser_test.go
  pkg/lightning/mydump/region.go
  tidb-lightning.toml
Labels: component/import, size/XL, status/LGT2, status/can-merge, type/enhancement

#1094 cdclog: fix the lost ddl files
  pkg/restore/log_client.go
  pkg/restore/log_client_test.go
Labels: cherry-pick-approved, component/cdc-restore, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#1285 restore: Fix restore data size
  pkg/metautil/metafile.go
  pkg/restore/client.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  tests/br_300_small_tables/run.sh
Labels: component/restore, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#1318 tests: outdated setting `--ratelimit` slow down CI time
  pkg/task/common.go
  tests/br_tikv_outage/run.sh
  tests/br_tikv_outage/workload
Labels: cherry-pick-approved, size/XS, status/LGT2, status/can-merge

#1328 build: fix build after different PR merged.
  pkg/task/common.go
Labels: cherry-pick-approved, release-blocker, size/XS, status/LGT2, status/can-merge

#1339 update tidb
  go.mod1
  go.sum1
  pkg/backup/client_test.go
  pkg/mock/mock_cluster.go
Labels: size/M, status/LGT2, status/can-merge

#1338 tests: refine the br_log_restore test
  tests/br_log_restore/run.sh
Labels: component/cdc-restore, component/test, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge

#1333 Remove unnecessary speed and concurrent limitation
  tests/br_backup_empty/run.sh
  tests/br_backup_version/run.sh
  tests/br_case_sensitive/run.sh
  tests/br_clustered_index/run.sh
  tests/br_db/run.sh
  tests/br_db_online/run.sh
  tests/br_db_online_newkv/run.sh
  tests/br_db_skip/run.sh
  tests/br_debug_meta/run.sh
  tests/br_full_ddl/run.sh
  tests/br_full_index/run.sh
  tests/br_history/run.sh
  tests/br_incremental/run.sh
  tests/br_incremental_ddl/run.sh
  tests/br_incremental_index/run.sh
  tests/br_incremental_only_ddl/run.sh
  tests/br_incremental_same_table/run.sh
  tests/br_insert_after_restore/run.sh
  tests/br_key_locked/run.sh
  tests/br_move_backup/run.sh
  tests/br_other/run.sh
  tests/br_s3/run.sh
  tests/br_shuffle_leader/run.sh
  tests/br_shuffle_region/run.sh
  tests/br_single_table/run.sh
  tests/br_skip_checksum/run.sh
  tests/br_split_region_fail/run.sh
  tests/br_table_partition/run.sh
Labels: first-time-contributor, size/M, status/LGT2, status/can-merge

#1273 test: Add TDE feature test
  tests/_utils/run_services
  tests/br_restore_TDE_enable/run.sh
  tests/br_restore_TDE_enable/workload
  tests/config/root.cert
  tests/config/root.key
  tests/config/tikv.toml
Labels: component/test, size/L, status/LGT2, status/can-merge

#1330 lightning: fix parquet parser for decimal type (#1272)
  pkg/lightning/mydump/examples/test.parquet
  pkg/lightning/mydump/parquet_parser.go
  pkg/lightning/mydump/parquet_parser_test.go
Labels: do-not-merge/cherry-pick-not-approved, size/XL, status/LGT2, status/can-merge

#1355 Print error log into log file instead of terminal
  pkg/restore/systable_restore.go
Labels: size/XS, status/LGT2, status/can-merge

#1353 storage: Add support for gcs for Lightning
  pkg/lightning/config/config.go
  pkg/storage/gcs.go
  pkg/storage/gcs_test.go
  tests/lightning_gcs/config.toml
  tests/lightning_gcs/run.sh
Labels: size/XL, status/LGT2, status/can-merge

#1286 test: fix unstable test checkpoint-parquet
  tests/lightning_checkpoint_parquet/run.sh
Labels: component/import, component/test, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#1367 test: Fix br_300_small_tables bug
  tests/br_300_small_tables/run.sh
Labels: needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge

#1329 lightning/mydump: support using custom terminator with strict-format
  pkg/lightning/config/config.go
  pkg/lightning/mydump/csv_parser.go
  pkg/lightning/mydump/region.go
  pkg/lightning/mydump/region_test.go
Labels: size/L, status/LGT2, status/can-merge

#1371 lightning: fix incorrect seek of duplicate iter
  pkg/lightning/backend/local/iterator.go
  pkg/lightning/backend/local/iterator_test.go
Labels: size/M, status/LGT2, status/can-merge

#1373 skip/remove check cluster has workload (isOnline)
  pkg/lightning/restore/check_info.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
Labels: component/import, needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge

#1343 pkg/membuf: refine bytesBuf to membuf
  pkg/lightning/backend/kv/session.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/manual/allocator.go
  pkg/manual/manual.go
  pkg/membuf/buffer.go
  pkg/membuf/buffer_test.go
  pkg/restore/ingester.go
  pkg/utils/bytes.go
Labels: size/XXL, status/LGT2, status/can-merge

#1354 tests: fix rawkv build
  tests/br_rawkv/client.go
Labels: size/M, status/LGT2, status/can-merge

#1379 *: Create SECURITY.md
  SECURITY.md
Labels: first-time-contributor, size/M, status/LGT2, status/can-merge

#1332 *: refine some code and comments according to golangci-lint
  cmd/tidb-lightning/main.go
  pkg/backup/client.go
  pkg/backup/schema_test.go
  pkg/checksum/executor_test.go
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/tidb/tidb_test.go
  pkg/lightning/restore/check_info.go
  pkg/lightning/restore/checksum.go
  pkg/lightning/restore/meta_manager.go
  pkg/lightning/restore/meta_manager_test.go
  pkg/lightning/restore/restore_test.go
  pkg/metautil/metafile.go
  pkg/restore/client.go
Labels: size/M, status/LGT2, status/can-merge

#1320 lightning: emit scan region log
  pkg/lightning/backend/local/localhelper.go
Labels: component/import, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#1384 Split code of `restore.go`
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/table_restore.go
Labels: size/XXL, status/LGT2, status/can-merge

#1386 go.mod:update tidb & tikv-client to new version
  go.mod1
  go.sum1
  pkg/backup/client.go
  pkg/backup/client_test.go
  pkg/conn/conn.go
  pkg/lightning/backend/kv/session.go
Labels: size/M, status/LGT2, status/can-merge

#1393 lightning: fix unstable configlist test
  pkg/lightning/config/configlist_test.go
Labels: size/XS, status/LGT2, status/can-merge, type/bug-fix

#1331 lightning: prettify data check error output
  pkg/lightning/restore/check_info.go
  pkg/lightning/restore/restore.go
Labels: size/L, status/LGT2, status/can-merge

#1398 testing: fix some race conditions in test
  pkg/lightning/lightning_test.go
  pkg/lightning/restore/checksum_test.go
  pkg/restore/batcher_test.go
Labels: component/test, size/S, status/LGT2, status/can-merge
