Repository pingcap/br, pull requests merged in 2021-05, with the labels that each got.

#1069 cdclog: fix lost delete
  pkg/kv/kv.go
  pkg/restore/ingester.go
  tests/br_log_restore/run.sh
Labels: size/S, status/LGT2, status/can-merge

#929 br/restore: add version check for backup schema_version
  pkg/conn/conn.go
  pkg/task/restore.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: component/restore, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, status/LGT2, status/can-merge, status/ptal

#1098 pd: Add pd request retry logic (#1088)
  pkg/pdutil/pd.go
  pkg/pdutil/pd_test.go
Labels: cherry-pick-approved, size/M, status/LGT2, status/can-merge, type/cherry-pick-for-release-4.0

#1103 *: update tidb
  go.mod1
  go.sum1
  pkg/checksum/executor.go
  pkg/lightning/restore/checksum_test.go
Labels: size/M, status/LGT2, status/can-merge

#1113 *: update pull request template
  .github/pull_request_template.md
Labels: size/XS, status/LGT2, status/can-merge

#1114 lightning: always enable `autocommit` in db connection
  pkg/lightning/restore/tidb.go
  tests/lightning_alter_random/run.sh
Labels: component/import, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, status/LGT2, status/can-merge

#1105 lightning: fix encode kvs size greater than 4.0g caused pebble panic
  pkg/lightning/backend/kv/sql2kv.go
  pkg/lightning/backend/kv/types.go
  pkg/lightning/backend/noop/noop.go
  pkg/lightning/backend/tidb/tidb.go
  pkg/lightning/restore/restore.go
  pkg/lightning/restore/restore_test.go
  tests/lightning_checkpoint_parquet/run.sh
Labels: component/import, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, status/LGT2, status/can-merge

#1076 err_msg: clarify some ambiguous error message
  cmd/br/restore.go
  errors.toml
  pkg/backup/client.go
  pkg/backup/push.go
  pkg/conn/conn.go
  pkg/errors/errors.go
  pkg/gluetikv/glue.go
  pkg/summary/collector.go
  pkg/task/backup.go
  pkg/task/backup_raw.go
  pkg/task/common.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
  pkg/utils/permission.go
  tests/br_log_test/run.sh
  tests/br_log_test/workload
Labels: size/L, status/LGT2

#1115 lightning: avoid ignore error when import data fails
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/localhelper.go
  pkg/lightning/backend/local/localhelper_test.go
  pkg/lightning/restore/restore.go
Labels: component/import, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, status/LGT2, status/can-merge

#1086 test: fix lighting unit test TestBatchSplitRegionByRanges and a panic issue
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/localhelper_test.go
Labels: component/import, component/test, needs-cherry-pick-release-5.0, size/M, status/LGT2, status/can-merge

#1139 pkg: use the GoTimeToTS() from oracle pkg
  pkg/task/backup.go
Labels: size/XS, status/LGT2, status/can-merge

#1100 test: fix integration test unbound variable error
  tests/run.sh
Labels: component/test, size/XS, status/LGT2, status/can-merge

#1095 restore: fix restore system table bug && add some unrecoverable tables
  pkg/restore/systable_restore.go
  tests/br_systables/run.sh
Labels: size/S, status/LGT2, status/can-merge

#1116 pkg: update tidb
  go.mod1
  go.sum1
  pkg/kv/session.go
  pkg/lightning/backend/kv/session.go
Labels: size/S, status/LGT2, status/can-merge

#1120 backup/checksum: add cluster index support for ranges
  pkg/backup/client.go
  pkg/backup/client_test.go
  pkg/checksum/executor.go
  pkg/checksum/executor_test.go
  tests/run.sh
Labels: contribution, first-time-contributor, needs-cherry-pick-release-5.0, size/L, status/LGT2, status/can-merge

#1089 lightning/restore: support ingset multi ssts for same range
  go.mod1
  go.sum1
  pkg/lightning/backend/local/local.go
  pkg/lightning/backend/local/local_test.go
  pkg/lightning/backend/local/localhelper.go
  pkg/logutil/logging.go
  pkg/restore/client.go
  pkg/restore/import.go
  pkg/task/restore.go
  pkg/task/restore_raw.go
Labels: component/import, component/restore, size/XL, status/LGT2

#1151 tests: add row count check for br clustered index tests
  tests/br_clustered_index/run.sh
Labels: size/S, status/LGT2, status/can-merge

#1148 pkg/lightning: let batch split keys also consider the raft entry limit (#905)
  pkg/lightning/backend/local/localhelper.go
  pkg/lightning/backend/local/localhelper_test.go
Labels: cherry-pick-approved, component/import, size/L, status/LGT2, type/bug-fix, type/cherry-pick-for-release-5.0
